### ISSUE TITLE
[Bug] Insane fire rate on a non-gatling gun

### ISSUE THREAD

**Issue by SabreMania** [tsunamayo/Starship-EVO#1833] opened 2020-04-24 15:44 UTC
Okay, so while I still haven't completely tested -every- single possibility yet, I am pretty sure that this is how the bug works.

If you place down a laser weapon and give it the Overcharge add-on (The one that makes your reload slower but also allows you to shoot two projectiles instead of one), and that your gun eventually finds itself unable to fire because your ship is in the way (talking about a turret specifically), when it is free to fire again, it will unleash an almost unending volley of projectiles at very, very quick intervals. 

What I think is happening is the gun stores more and more 'charges' in the gun, which would normally fire it off immediately, because it is prevented from shooting by the presence of the ship's hull, or another child entity, being there.

This was tested with an AI trying to fire at a target. I have not tested if this works manually.

Edit: I know that some people have managed to obtain a similar effect, but through logic. I couldn't detail how exactly, as I haven't managed to make it work.

### Steps to reproduce the issue:

Place down a turret with the supercharge add-on, have it track a target that is behind the hull, and then allow it to fire by re-angling the ship, or alternatively waiting for the enemy target to get back in a valid firing angle.

If this doesn't work, try adding the recoil barrel. It is the one I used during my tests.

...

### Environment
- Skywanderers version: 20w17c
- Graphics Card: GTX 970

**Comment by hl2shadowslayer** [comment] 2020-04-24 19:04
Me and Nuclear achieved the same effect by making a two brick-long laser, attaching two small charge addons, and attaching a cooling barrel. It doesn't need to be on a turret, and it can be done with manual fire. In our case, it seems that the cooling barrel for some reason prevents two brick-long lasers from firing. Once the barrel is removed, it unleashes everything at once. Me and Zach made a video demonstrating it https://youtu.be/UROnGOPAasU

**Comment by tsunamayo** [comment] 2020-04-25 00:54
Okay great video ;) I keep you posted!

**Comment by tsunamayo** [comment] 2020-04-26 23:24
@SabreMania @hl2shadowslayer just to confirm, I cant reproduce the issue on 20w17e. In any case issue will be fixed for next patch, as volley mechanism is being removed. Cheers!

**Closed by tsunamayo** 2020-04-26 23:24 UTC
Labels: Bug
