### ISSUE TITLE
[BUG] Building on terrain sinks with each click 

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Starship-EVO#1852] opened 2020-04-25 10:59 UTC
When you delete the starter block from the terrain build, every time you place or delete a block from the structure the structure will start to sink into the terrain, it is very minimal at first but becomes noticeable over time. 

...

Reproducing issue:  

   -Place starter block on terrain 
   -Build something simple with blocks on top of it
   -Place and delete a block to simulate continual building 
   -Notice the slight quicksand effect with each manipulation to the building 
...

- Skywanderers version: 20w17d
- Graphics Card: 1080ti

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4532820/output_log.txt)

**Comment by tsunamayo** [comment] 2020-04-25 11:33
Yes correct, actually a duplicate of #1849. I am on it!

**Comment by tsunamayo** [comment] 2020-04-25 13:06
Okay issue fixed for 20w17e. Patch is coming asap as it is a serious issue. Cheers

**Closed by tsunamayo** 2020-04-25 13:06 UTC
Labels: Bug
