### ISSUE TITLE
Gravity unit graphical bug when in hotbar

### ISSUE THREAD

**Issue by Starwhip** [tsunamayo/Starship-EVO#2003] opened 2020-05-09 00:38 UTC
When holding gravity units, the entire build becomes shaded in pink and the gravity fields do not appear. The outline for the block placement also does not appear. The issue goes away if you have another block/brick selected on the hotbar but reappears whenever holding the generator.

### Environment
- Starship EVO version: 20w19d
- Graphics Card: Radeon RX 580

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4602341/output_log.txt)
![20200508203237_1](https://user-images.githubusercontent.com/36343006/81459042-c9b79000-916b-11ea-88dc-c33685275161.jpg)
![20200508203239_1](https://user-images.githubusercontent.com/36343006/81459044-cae8bd00-916b-11ea-9563-109f85c1ba7d.jpg)
![20200508203604_1](https://user-images.githubusercontent.com/36343006/81459045-cb815380-916b-11ea-82aa-8e52bce1bcc3.jpg)
![20200508203609_1](https://user-images.githubusercontent.com/36343006/81459046-cc19ea00-916b-11ea-8c30-b3df7da89965.jpg)

**Comment by alxnns1** [comment] 2020-05-09 01:01
duplicate of https://github.com/tsunamayo/Starship-EVO/issues/1996

**Comment by tsunamayo** [comment] 2020-05-09 01:15
Yes, thanks for reporting that issue was already fixed,  will be in next patch 20w19e. Cheers

**Closed by tsunamayo** 2020-05-09 01:15 UTC
Labels: Bug
