### ISSUE TITLE
[Bug] Brick placement "through" other bricks [20w06a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1604] opened 2020-02-15 09:14 UTC
### Short Description of the issue:
The brick highlighted during placement is sometimes on the far side of the one that should be highlighted for placement.

### Steps to reproduce the issue:
Place a large flat brick, then place another, smaller brick on top of it; this makes it easy to see the effect. Now try to place a third brick on the second brick from various angles. The game will sometimes refuse to highlight the top brick, instead highlighting the one on the other side of it first. Interestingly, deleting the rearmost brick will then allow the game to "see" the nearer one.

### Environment
- Skywanderers version: 20w06a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
The game cannot "see" the nearer brick here, and is trying to place a new one on the further brick:
![20200215030953_1](https://user-images.githubusercontent.com/33041786/74585296-c06dbb80-4fa0-11ea-8498-f87392d853a7.jpg)

However, if we delete the further brick (which is still highlighted):
![20200215030957_1](https://user-images.githubusercontent.com/33041786/74585313-fca11c00-4fa0-11ea-96ea-b56c70d7da5a.jpg)

The game can now "see" the nearer one, without needing to move the cursor from the position it was in when deleting the further brick:
![20200215030959_1](https://user-images.githubusercontent.com/33041786/74585317-01fe6680-4fa1-11ea-9401-fbe8ccc325ae.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4208247/output_log.txt)

**Comment by tsunamayo** [comment] 2020-02-28 05:21
Okay I cant reproduce this, could you send me a bp? Are you able to reproduce 100% of the time when at the right angle? Thanks

**Comment by tsunamayo** [comment] 2020-03-29 04:21
@Dwarf-LordPangolin hey I dont know if you faced this again in latest build. Thanks

**Comment by tsunamayo** [comment] 2020-10-15 00:39
I think this should be fixed now. Thx

**Closed** 2020-10-15 00:39 UTC
Labels: Bug
