### ISSUE TITLE
I can't jump to another system.

### ISSUE THREAD

**Issue by Aranhanauta** [tsunamayo/Starship-EVO#5445] opened 2024-01-26 00:42 UTC
### Short Description of the issue:

I can't jump to another system. The ship tries to align but it keeps rocking forever and never stops.

### Steps to reproduce the issue:
1 - try go to another system normaly.
2 - Activate the warp core.
3 - The ship try to align but it keeps rocking forever and never stops.

### Environment
- Starship EVO version: 24w04a
- Graphics Card: AMD Radeon HD 8370D

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment] 2024-01-26 01:47
@Aranhanauta Hi, could you send me your blueprint? Thanks

**Comment by Aranhanauta** [comment] 2024-01-26 03:14
Sorry I do not understand. You need me to send you the steps to reproduce the issue.

**Comment by tsunamayo** [comment] 2024-01-26 03:54
@Aranhanauta Hi, I need the spaceship, it might be spaceship related:

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\
You will need to zip the folder to upload it.
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Tackietacktack** [comment] 2024-01-26 09:45
I had that too, did you enable both warp and light cruise?
That was the cause for me

**Comment by Aranhanauta** [comment] 2024-01-26 11:07
It happens with any ship I use, it doesn't have a specific project. My warp doesn't work, whether it triggers lightcruise or not.

**Comment by Aranhanauta** [comment] 2024-01-26 11:09
Out of curiosity: could this bug be related to low FPS? Because my video card is not ideal for running the game. If I replaced it with a better one, would that solve the problem?

**Comment by ProPeach** [comment] 2024-01-26 11:27
You could also upload a ship to the Workshop and post the link here if it's easier, that'd help diagnose the issue. Even if it happens on the ships you've tried so far, there may be a common thread there

**Comment by Aranhanauta** [comment] 2024-01-26 11:32
I don't think the problem is with the ship itself. Maybe it's my computer configuration. Because I haven't built any ships, so far I've only used the pre-made models that the game offers.

**Comment by Aranhanauta** [comment] 2024-01-26 14:04
I don't think the problem is with the ship itself. Maybe it's my computer configuration. Because I haven't built any ships, so far I've only used the pre-made models that the game offers.

**Comment by Aranhanauta** [comment] 2024-01-26 18:39
I noticed something today while I was playing. I locked a destination in Lightcruise and turned on automatic navigation. At one point during the journey, the ship was shaking like when I try to activate the warp, but then it straightened out. I think the problem may be with automatic navigation.

Remember, this happens with ANY ship I use, it doesn't have a specific project.

**Comment by Aranhanauta** [comment] 2024-01-28 22:53
Hello, I would like to know how it is going. I'm trying to find the error to make your work easier. I know you're very busy, but I just wanted to know a little more

**Comment by Tackietacktack** [comment] 2024-01-31 18:36
you have right, warp don´t work.

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14115726/Player.log)
[cockpit 17.zip](https://github.com/tsunamayo/Starship-EVO/files/14115734/cockpit.17.zip)

**Comment by Aranhanauta** [comment] 2024-01-31 19:09
I don't understand what these files mean. Were you also unable to jump to another system?

**Comment by Tackietacktack** [comment] 2024-01-31 20:03
yes, files are for tsuna to find the bug

**Comment by Aranhanauta** [comment] 2024-01-31 20:31
Oh, Nice!

**Comment by tsunamayo** [comment] 2024-02-05 00:19
@Aranhanauta Hi, I cant say for sure but you mentioned low-fps, so I would guess the ship cannot lock to the star and never jump. I will try to reproduce, thanks

**Comment by Aranhanauta** [comment] 2024-02-05 00:24
Thak you

**Comment by tsunamayo** [comment] 2024-02-13 03:40
@Tackietacktack @Aranhanauta Hi, so the issue should be fixed for 24w07a. Thanks!

**Closed by tsunamayo** 2024-02-13 03:40 UTC
Labels: Bug, Cannot Reproduce
