### ISSUE TITLE
[BUG] Target Retile [w20d20]

### ISSUE THREAD

**Issue by JRL101** [tsunamayo/Starship-EVO#2083] opened 2020-05-16 13:42 UTC
### Short Description of the issue:
no dot or circle for where im aiming, was there ever one?
...

### Steps to reproduce the issue:
???
...

### Environment
- Starship EVO version: w20d20
- Graphics Card: GTX1080

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by Majikmonster** [comment] 2020-05-16 15:55
Currently there is no default aiming reticle. The only way to have one is to build one.

It's not a bug that one doesn't exist, but it would be nice to have it.
This ticket is a suggestion (desired feature)

**Comment by JRL101** [comment] 2020-05-16 16:01
> 
> 
> Currently there is no default aiming reticle. The only way to have one is to build one.
> 
> It's not a bug that one doesn't exist, but it would be nice to have it.
> This ticket is a suggestion (desired feature)

 Incorrect, the reticule has existed, was looking through screenshots, also remember more recently including the "hold" circle fore getting in and out of chairs and controls. See screenshot below:
![20190604141414_1](https://user-images.githubusercontent.com/33255536/82124376-46ccb000-97d1-11ea-92b3-0e4c22176c0e.jpg)

**Comment by JRL101** [comment] 2020-05-16 16:04
Also found a screenshot of Pre-alpha 20w17c with the newer design 

_STEAM:HeroSci_
![image](https://user-images.githubusercontent.com/33255536/82124482-e12cf380-97d1-11ea-9aad-138e294ec594.png)

**Comment by JRL101** [comment] 2020-05-16 16:36
Interesting, seems to have been restored after a clean install. Strange.

**Comment by ultrak2k** [comment] 2020-05-16 17:24
Oh you mean the HUD aiming one, I’ve avtually seen that disappear too but I think that’s after I get the bug where everything in the system is shifted around. Or not, but I know I get it

**Comment by tsunamayo** [comment] 2020-05-16 22:52
@JRL101 Yes I think that you got a corrupted install... Glad it is fixed now.

**Closed by tsunamayo** 2020-05-16 22:52 UTC
Labels: Bug
