### ISSUE TITLE
weird new world

### ISSUE THREAD

**Issue by luckyrada** [tsunamayo/Starship-EVO#3548] opened 2021-01-29 03:00 UTC
### Short Description of the issue:

spawned into new world i just created, and i get no halo ring. no sun, just a planet and three.... light sources? pictures attached

edit: reloading the world seemed to fix it.... except it spawned me in the sun lol i had to use speed keys to escape
### Steps to reproduce the issue:

make new world and load it

### Environment
- Starship EVO version: 21w03c
- Graphics Card: intel(r) iris(r) plus graphics 655

### Additional information:

![20210128185211_1](https://user-images.githubusercontent.com/46651990/106225981-0d8b7300-619b-11eb-8bd7-0dee5ef9c015.jpg)

i cant upload player.log it says it dosnt suport that file type :/

**Comment by tsunamayo** [comment] 2021-01-29 03:08
@luckyrada Hi, you have to zip the log file...

**Comment by luckyrada** [comment] 2021-01-29 03:18
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/5891386/Player.log)
ah there

**Comment by tsunamayo** [comment] 2021-02-04 04:03
@luckyrada Do you get this issue every time you create a new character? I cant reproduce... Thanks

**Comment by Jorpis-Jorah** [comment] 2021-09-28 17:55
It's probably just the seed, if it happens again. Create a new world with a different seed. The problem should be fixed. Thanks.

**Closed** 2022-01-28 06:39 UTC
Labels: Bug, Cannot Reproduce
