### ISSUE TITLE
[Bug] Missing paintable materials on existing blocks when spawning Blueprint

### ISSUE THREAD

**Issue by zalexville** [tsunamayo/Starship-EVO#4923] opened 2022-09-22 00:05 UTC
### Short Description of the issue:

Unable to see materials (Copper, Steel, Silver, etc) on existing blocks. Able to see and paint/remove on any newly placed blocks.

Issue first appeared in May, waited to make a post since new update was imminent. I checked last night and again today, the issue is still present. I have checked a few other blueprints, this is the only one I have found that has this issue. 

### Steps to reproduce the issue:

Issue appears when spawning in blueprint. 

### Environment
- Starship EVO version: 22w38a
- Graphics Card: Nvidia RTX 3060 12gb

### Additional information:

Correct Door:
![20220429162536_1](https://user-images.githubusercontent.com/65626266/191630015-9b7fd5a5-b789-4d4f-b1e0-ace0a231a148.jpg)

Incorrect Door:
![20220921195543_1](https://user-images.githubusercontent.com/65626266/191630030-dcde0819-ef44-4b36-879c-43ecdf85ae59.jpg)

Player Log: 
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9621084/Player.log)

Ship Blueprint:
[Starfleet Ulaan-Class Refit.zip](https://github.com/tsunamayo/Starship-EVO/files/9621089/Starfleet.Ulaan-Class.Refit.zip)

**Comment by Servomotor** [comment] 2022-09-22 23:47
I am having the same issue. 

Steps to reproduce the issue:
Spawn this blueprint from the workshop. 
https://steamcommunity.com/sharedfiles/filedetails/?id=2741806620

Environment
Starship EVO version: 22w38a
Graphics Card: Nvidia RTX 2080 8g

The Captain Ahd's ship I made some time ago now has parts of the ship that were painted silver showing up as black. 



This is what it looks like now if you download it off  the workshop.
![20220922184220_1](https://user-images.githubusercontent.com/65745916/191869916-34cf39b2-d1c3-488e-9b3c-bf925e742d93.jpg)



this is what the ship is supposed to look like. 
![20220922184238_1](https://user-images.githubusercontent.com/65745916/191869932-481111d2-fa78-4e60-8452-8e3fb5ddc6b6.jpg)

**Comment by zalexville** [comment] 2022-10-02 03:18
Update: I did a full reinstall of the game. Only thing backed up was my save data containing blueprints and prefabs. The issue is still present.

**Comment by zalexville** [comment] 2022-10-02 21:05
I found a work-around. I had to check "Material Removes Paint" in F1 to be able to remove and add it again to my ship. I was also able to save the ship with the fix material. It had removed the material and replaced it all as black paint, which is why I couldn't redo it until I checked the box. Still unknown what caused all my materials to change to black paint to begin with.

**Comment by tsunamayo** [comment] 2022-11-09 01:32
@zalexville @Servomotor Hi, this issue will be fixed for 22w45a. Thanks a lot!

**Closed by tsunamayo** 2022-11-09 01:32 UTC
Labels: Bug
