### ISSUE TITLE
[BUG] Major FPS drop in other stars besides home base, UNLESS in lightspeed inside of the system

### ISSUE THREAD

**Issue by StarrKiss** [tsunamayo/Starship-EVO#3117] opened 2020-10-24 16:36 UTC
### Short Description of the issue:
Upon going to any system besides the spawn system, the FPS plummets from ~160 fps to 20. This occurs without exception in every other system. HOWEVER, if you hold L to go to the hyperspeed inside the system (NOT the warp jump between systems) the fps goes back to normal. But the moment you LEAVE hyperspeed, anywhere within the system, the FPS tanks once more.
### Steps to reproduce the issue:

1. Warp to any system
2. Observe FPS
3. Go to hyperspeed inside system and repeat step 2

### Environment
- Starship EVO version: 20w43a
- Graphics Card: GTX 1070 ti

EDIT- here is the output log
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5433300/output_log.txt)

This output log was in the same session as #3116

**Comment by tsunamayo** [comment] 2020-10-25 23:42
@StarrKiss Hi, was it during a mp session? Thanks

**Comment by StarrKiss** [comment] 2020-10-25 23:49
Sort of- I opened the game to MP, found out rapidly it didn't work, then closed it to MP and messed around @tsunamayo and that was where I found both of these problems

**Comment by tsunamayo** [comment] 2020-10-25 23:51
@StarrKiss okay. Do you reproduce the issue when simply starting the game alone? Also when you arrive in a new system, do you do something special? I cant reproduce this issue... Cheers

**Comment by StarrKiss** [comment] 2020-10-26 00:08
@tsunamayo  I can reproduce this pretty regularly but not 100% of the time in non MP seessions.

**Comment by tsunamayo** [comment] 2020-10-26 00:22
@StarrKiss okay mate I finally was able to reproduce this one, it will be fixed for 20w44a. Thanks!

**Closed by tsunamayo** 2020-10-26 00:22 UTC
Labels: Bug
