### ISSUE TITLE
[Bug] 22w42a - Fuel does not refill even when refill options are being used

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#4971] opened 2022-10-22 14:44 UTC
### Short Description of the issue:

I've noticed that my ship slowly started to slow down during flight and became unresponsive to the movement commands.
I realised that reactors do not refill fuel automatically even when the corresponding auto-refill function is enabled.
The Rerfill Tanks button in the Codex also doesn't refill the internal reactor tanks.
I have no idea if the issue pertains to subsystems other than reactors but it might be worth investigating if the bug has something to do with the refill function as a whole, or is it just the reactors.

### Steps to reproduce the issue:

1. Launch the game in the Experimental version
2. Load the save provided
3. Get a hold of the yoke in front of the character and try to pilot the ship - notice it's immovable
4. Get out of the yoke and turn around to inspect the reactors
5. Click the reactors and notice their empty fuel level

### Environment
- Starship EVO version: 22w42a
- Graphics Card: 970M

### Additional information:

[Save file](https://github.com/tsunamayo/Starship-EVO/files/9844598/22w38c.zip)

**Comment by Kaiser-Indrasil** [comment] 2022-10-22 19:00
I've also noticed that the fuel present in the Ractors and Lightcruise Engines does not contribute towards the total fuel entity data present in the Codex.

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9845097/Player.log)

![image](https://user-images.githubusercontent.com/63756057/197358082-90d1b9b8-a766-416e-9465-29059378eab0.png)

**Comment by Kaiser-Indrasil** [comment] 2022-10-23 11:12
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9846377/Player.log)
[Astero Neovox - Broken Fuel.zip](https://github.com/tsunamayo/Starship-EVO/files/9846375/Astero.Neovox.-.Broken.Fuel.zip)

I've also noticed that during Lightcruise my ship suddenly started losing speed.
Upon inspection of Lightcruise Engines, I've noticed that they can have negative value to their fuel levels:

![image](https://user-images.githubusercontent.com/63756057/197388372-3355e3be-091f-4257-bb2b-cfc465f2b337.png)

Also, if you look at how the Lightcruise speed indicator changes, you can see an interval of a few seconds.
Coincidentally, this is the refresh rate of fuel levels in Lightcruise Engines, Reactors, and Fuel Tanks.

https://user-images.githubusercontent.com/63756057/197388723-4ba6587e-fe5d-4da2-b26b-872e8d74afec.mp4

**Comment by tsunamayo** [comment] 2022-10-31 04:22
@Kaiser-Indrasil Hi, it should be fixed for 22w43a. (I was not able to reproduce beforehand so tell me if it is still not fixed).
Thanks

**Closed by tsunamayo** 2022-10-31 04:22 UTC
Labels: Bug
