### ISSUE TITLE
Light flickering 

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#4704] opened 2022-05-15 08:29 UTC
It's a weird visual effect that really hurts my eyes because of it's constant flickering nature. 
My screen visuals change pretty much between these 3 effetcs:

normal:
![20220515100719_1](https://user-images.githubusercontent.com/81495956/168463854-ab8ee158-7089-4b0d-979f-d6f583718e01.jpg)

when flickering:
![20220515100707_1](https://user-images.githubusercontent.com/81495956/168463868-ddec81a4-9e36-43dd-ae42-a161a99746c2.jpg)
![20220515100550_1](https://user-images.githubusercontent.com/81495956/168463897-00b1f738-39ca-44ca-adef-c49aa3ed8645.jpg)

**Comment by ProPeach** [comment] 2022-05-16 16:42
I've found it's only present where lights have been placed and cast shadows. Here's a repeatable test case - 
https://youtu.be/7Rr_Pja8CQc
[Light Flickering Bug.zip](https://github.com/tsunamayo/Starship-EVO/files/8701837/Light.Flickering.Bug.zip)

To reproduce -
- Enable "Box Delete Decals Only" in the F1 menu
- Select the wall with the Delete Tool
- Delete

As more decals are removed, the effect worsens

I've no idea why this test case specifically works, this is an old blueprint before neovox so I was just cleaning all the decals left over from the voxel paint conversion when I noticed it produces the effect reliably

**Comment by BigBadKangaroo** [comment] 2022-05-16 18:09
That's interesting ... I got this bug without even using decals at all. I didn't even use the box delete tool that day.
I only placed down some lights seen in the screenshots.
I'll test around with lights just like I did when it happend to me to see if I can reproduce it that way.

**Comment by ProPeach** [comment] 2022-05-16 18:33
I've found it happens when I start placing lights as well, just not exactly all the time so I figured a repeatable blueprint test case was better than me just saying "spam a bunch of lights until something happens" lol

**Comment by BigBadKangaroo** [comment] 2022-05-16 20:57
I've tried some things out but I actually couldn't reproduce this one intentionally.
Might even be linked to the brick flickering I reported in the news thread.
I have the feeling that the flickering just starts if I play for "too long" in one session

**Comment by tsunamayo** [comment] 2022-05-24 02:09
Hi, okay thanks for the bp and test case I will try to reproduce.

**Comment by BigBadKangaroo** [comment] 2022-06-04 12:45
Here's a little update on this bug:

I can reproduce this pretty reliable when deleting large amounts of blocks with the box delete tool.
I'm talking about a couple of hundered blocks.
On the spots where the flight flickering is, I placed some custom thrusters and deleted them with the box delete tool. After deleting them the bug occurred

In addition: After deleting and letting things go for a couple of minutes, the light flickering seems to be "stuck" to the BP where things have been deleted! Even after moving the ship the bug is "stuck" to the spot on the ship.

![20220604135737_1](https://user-images.githubusercontent.com/81495956/171999409-177016e1-bf7b-4f31-af20-d6f67b350aa6.jpg)
![20220604135801_1](https://user-images.githubusercontent.com/81495956/171999421-c3b82542-7869-4798-9e98-a0d6ff0719bb.jpg)
![20220604142803_1](https://user-images.githubusercontent.com/81495956/171999426-302359ed-d0fc-4615-bf10-fb8255819e8e.jpg)

**Comment by tsunamayo** [comment] 2022-06-16 00:33
@BigBadKangaroo @ProPeach  I think this bug should be fixed in the current build. Could you tell me if you reproduce? I tried your test case, it was fine but I am not sure to have delete exactly the right thing.
Thanks

**Comment by ProPeach** [comment] 2022-06-16 00:40
@tsunamayo I think this one is fixed! I haven't noticed it happening in places with lights, and I agree the test case blueprint is also not reproducing the bug. Looks like it is fixed in 22w23a : )

**Comment by tsunamayo** [comment] 2022-06-16 01:25
Okay cool to hear!

**Closed by tsunamayo** 2022-06-16 01:25 UTC
Labels: Bug
