### ISSUE TITLE
[BUG] Multiplayer warping when you release the ship controls

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#1859] opened 2020-04-25 17:00 UTC
### Short Description of the issue:
If anyone other than the host releases a ship's control, it is violently accelerated away with the ship and rotates like crazy.
### Steps to reproduce the issue:
Join a multiplayerserver. Fly a ship and release the joystick.

### Environment
- Skywanderers version: 20w17e
- Graphics Card: gtx 1070 mobile

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4533557/output_log.txt)

**Comment by tsunamayo** [comment] 2020-04-26 07:01
@Battlepixel I cant reproduce the issue. Was it with a specific ship? Where you flying in a specific mode or in Standard 6dof? Was the auto-pilot locked? Also is it something you reproduce all the time?
Thanks!

**Comment by Battlepixel** [comment] 2020-04-26 07:11
The bug occurs on all ships. We also tried to change the host, but the problem remained for everyone who wasn't host.

**Comment by tsunamayo** [comment] 2020-04-26 07:34
@Battlepixel okay thanks, also how many were you guys on the server? Once the ship went off it was for everybody? Thanks

**Comment by Battlepixel** [comment] 2020-04-26 07:56
Yesterday we were only two but we know the bug also from previous versions. The bug is visible to everyone on the server. When I go close to the ship as a host, I jump and rotate with the ship even though the bug was not caused by me but by the pilot(not host).

**Comment by tsunamayo** [comment] 2020-04-26 23:48
Okay I think this will be fixed for 20w18a. Not sure 100% though as I was not able to reproduce consistently so I will wait for your confirmation. Thanks!

**Comment by tsunamayo** [comment] 2020-04-30 01:02
@Battlepixel tell me if you guys were able to reproduce that issue! Thanks

**Closed by tsunamayo** 2020-04-30 01:02 UTC
Labels: Bug
