### ISSUE TITLE
[Bug?] [20w20c] Entering ship yoke after editing turrets causes extreme performance drop

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2067] opened 2020-05-14 10:38 UTC
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4627694/output_log.txt)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4627944/output_log.txt)
(I included this second log after it happened again)
After changing some turret core links on 2 different ships, they both would create incredible lag when trying to activate the ship yoke afterwards.
The yoke would not bring up the ship HUD nor give control the ship (edit: can still use hotkeys). I could then continually re-enter the yoke and stack the number of times I had to hold F to exit it. All the while, the game's fps would choke and taking screenshots of the event made the game freeze for multiple seconds.
### Steps to reproduce the issue:
-enter the yoke of a ship with turrets (the blueprint I sent you for issue #2066 is a prime case)
-exit the yoke
-edit the turret core links
(setting the turret to auto-fire on ship target is what I had it set to at the time)
-repeat
### Environment
- Starship EVO version: 20w20c
- Graphics Card: Nvidia GeForce GTX 1060 6GB
In this image, the fps drop coincides with the turret activity (the bolts have hit the shield)
![20200514035547_1](https://user-images.githubusercontent.com/51390907/81924334-f8d76280-95ac-11ea-87d1-a0fe6b8b136b.jpg)
In the next 2 images, the yoke has failed to work properly, and the fps meter in the corner indicates a huge performance impact from something behind the scenes (the turrets also failed to work during that time)
![20200514060947_1](https://user-images.githubusercontent.com/51390907/81924710-7602d780-95ad-11ea-89dc-f7cbcf6e47a7.jpg)
![20200514061031_1](https://user-images.githubusercontent.com/51390907/81924718-78653180-95ad-11ea-9030-6fc2884ef1be.jpg)

**Comment by tsunamayo** [comment] 2020-05-15 02:25
you have the bug on two ships?  Could you send me the second one of it is smaller than the first one? Thanks

**Comment by tsunamayo** [comment] 2020-05-15 02:37
I cant reproduce the issue on the blueprint you sent me. Could you please give me a more precise how-to, ie which turret did you touch, and what did you changed?
There is clearly an issue in the log - it should be easy to fix once I manage to reproduce.
Thanks

**Comment by tsunamayo** [comment] 2020-05-19 02:50
@Majikmonster Hi, I would very much like to fix that issue as there is clearly something wrong. Do you know which turret should I touch to reproduce that issue? Thanks a lot!

**Comment by Majikmonster** [comment] 2020-05-31 03:29
It was any number of the turrets, but I think the worst happened after the front left of the small turrets on either ship were changed. I don't remember for certain.

**Comment by tsunamayo** [comment] 2020-11-26 05:42
This issue should be fixed as of today. Thanks

**Closed by tsunamayo** 2020-11-26 05:42 UTC
Labels: Bug
