### ISSUE TITLE
[bug] Lot's of bugs concerning mining, collector and cargo

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4939] opened 2022-09-25 00:52 UTC
I recorded a video that shows several bugs. So I updated it on youtube (not listed), and I'm gonna address each bug with a link to the video.

I know that you prefer each bug on separate post, but everything happened one after the other, and the game is freezing a lot!

**_1° bug: collecting sound repeating endlessly_**
https://youtu.be/Vusoiuy4FH8?t=210

A recurrent bug happens when an ore is attracted to a collector but doesn't unspawn into the ship storage. The ore remains inside the collector, but it doesn't disappear, and the game keeps repeating the same SFX. It only stops if you move your ship as fast as possible to get away from the non-collected ore.

**_2° bug: the collector is settled as expel, but it doesn't really release the ore_**
https://youtu.be/Vusoiuy4FH8?t=168

The collector spawns the ore, but it doesn't release the ore on the conveyor belt. The ore keeps floating in front of the expeler collector

**_3º bug: cargo doesn't show stored ores, even after collecting tons of ores_**
https://youtu.be/Vusoiuy4FH8?t=147

it's a recurrent problem. The cargo interface doesn't show any stored ore, and when you try to expel the content, it expels fewer ores from it than you had really collected.

**_4ºbug: sometimes the collector doesn't collect_**
https://youtu.be/Vusoiuy4FH8?t=184

When this happens, the ore isn't collected and keeps floating all around. some are affected by gravity, some don't.

**_5°bug: frozen screen_**
I don't know what is causing the frozen screen... 

https://youtu.be/Vusoiuy4FH8?t=325

**_6º warning: can't save the blueprint_**

I couldn't save the blueprint used in these experiments... the game has shown this warning message.

![image](https://user-images.githubusercontent.com/73253472/192123606-5e496192-4fcf-4079-994a-0fac6c7faeaf.png)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9639811/Player.log)
[experimental craft.zip](https://github.com/tsunamayo/Starship-EVO/files/9639813/experimental.craft.zip)

**Comment by tsunamayo** [comment] 2022-09-25 01:13
@Uncle-Ulty Thanks, I will have a look at it!

**Comment by tsunamayo** [comment] 2022-09-26 04:07
@Uncle-Ulty Hi, regarding 2) are you sure you dont have a pull field also active on the collector?
Thanks

**Comment by tsunamayo** [comment] 2022-09-26 04:32
@Uncle-Ulty regarding 4) I think it is normal, when there is no capacity left inside the collected it will stop pulling. I could change the behaviour to have it still pull if it is confusing, but in any case it wont collect.
Unfortunately I cant reproduce the other bugs. They might be linked, there might be an original bug that will then provoke all kind of weird behaviour related to items.
=> do you manage to reproduce any of the remaining bug as soon as you boot the game? Or does it happens after a while?
Thanks

**Comment by Uncle-Ulty** [comment] 2022-09-26 06:07
I can reproduce most of them anytime (the frozen screen is random)

**Comment by Uncle-Ulty** [comment] 2022-09-26 06:23
I tried to record a video showing a build built from zero, to show all the bugs, without any traces of previous storage items or anything else... but the game has frozen again.....

about the expel, I think there is something related to the expel speed... I'm not sure...

**Comment by Uncle-Ulty** [comment] 2022-09-26 16:23
Q:Hi, regarding 2) are you sure you dont have a pull field also active on the collector?
Thanks

A: that's the point, the expel collector holds the ores as it was a "draw in" collector.

Q: Regarding 4) I think it is normal when there is no capacity left inside the collected it will stop pulling.

A: ok. To check that we need to be able to see what is in the interior of storage... It seems it is one of the bugs

I think there are many bugs or one big and evil bug behind everything... it's difficult to determine what is causing the bugs...

**Comment by Uncle-Ulty** [comment] 2022-09-26 17:21
Also, when the game freezes, I can't even open the task manager to forcibly close Stevo. I need to log out win user or restart the computer...

heavy mining is causing crash... or the mining or something related to asteroid renderization

**Comment by Uncle-Ulty** [comment] 2022-09-26 17:44
I recorded the expeller collector behavior...

https://youtu.be/M6dWyVkjo5U

sometimes it ejects so fast that you only see a fast frame of the launched ore.

sometimes it doesn't hold of the ore, and it keeps floating in front of the expeller...

I really believe it is related to the expel speed...

also, the "zero speed" for the expeller collector should be a mode to only "drop" the ore, in front of the expeller collector, on a conveyor belt

**Comment by tsunamayo** [comment] 2022-09-27 02:04
@Uncle-Ulty Hi, not sure, could you send me the blueprint? You still have a pull range set, so it is a fight between the pull and the expel speed. I would expect in most cast when you want to expel you need to set the pull range to 0.
If you set a 0 speed then the ore will be dropped. If you still have a pull then it will be pulled again.

@Uncle-Ulty Regarding the freeze, how does it happen? Like right away or did you did something beforehand? Unfortunately inventory manipulation can result in freeze if there is a bug hidden somewhere. 
I also saw from the log an issue with the code that will construct the sentence you see when looking at an object. It must have been you looked at an "corrupted" object. That could have then triggered all sort of incoherency later on.

A bit tough to investigate be we will get to the hang of it!
Cheers

**Comment by Uncle-Ulty** [comment] 2022-09-27 02:36
I tested it with super basic builds (I zipped them and added them to this message) ...The expeller is acting strangely... some other guys are saying the expeller is expelling and pulling the same ore over and over...

About the frozen screen, it only happens when I'm close to an asteroid. And yes, as you can see in some videos, sometimes a section of the asteroid's surface disappears... Sometimes it takes too much time to load/render. Sometimes it only happens when I'm mining... So it seems to be related to the mining beam or to the asteroid...

There are too many variables at the same time. the recorded video shows exactly what I'm doing. So if you wanna know what is causing the bugs, just watch the video and you gonna know all the objects and possible variables.

cheers!

[experimental craft.zip](https://github.com/tsunamayo/Starship-EVO/files/9650960/experimental.craft.zip)


[Blueprints.zip](https://github.com/tsunamayo/Starship-EVO/files/9650957/Blueprints.zip)

**Comment by Uncle-Ulty** [comment] 2022-09-27 03:13
more crazy stuff....


Black cube.... ominous
![image](https://user-images.githubusercontent.com/73253472/192422942-9aef11b2-76c5-4ded-be2d-f25f1d0dbcb7.png)

**Comment by tsunamayo** [comment] 2022-09-28 22:25
@Uncle-Ulty Hi, are all the video recorded from the beginning of the session? Regarding the missing patch, again the problem is that the game load those from previous session, so it there was a bug it might have corrupted the save...
Can you go to your character save path and delete what is inside the Terrain folder?

Overall still hard to tell, I think we need to divide and conquer. Is it a mining issue, a crafting one? I fixed something that could explain some weirdness for the next patch.
Cheers

**Comment by DrizztCode** [comment] 2022-10-08 13:13
hi - i have encountered various issues with containers and inventory and hoses etc (hoses are awesome though, despite the bugs)

but specifically i have a video (unlisted) showing a quick way to get an inventory freeze - it will work on the habitat or on an asteroid - location isn't important

https://youtu.be/soLtx03kz90

the steps taken are in the description - but i will repeat them here - as well as a quick way to end the process once the game freezes, without having to sign out:

1. started a new game
2. skipped tutorial
3. clipped out of base, deactivated noclip, fast travelled to asteroid
4. spawned in repair pod with mining laser (not the one from the workshop lol - not sure why someone uploaded that - i just made it quickly for this test as a known ship with no inventory) 
5. mined and collected some rocks
6. started a new ship and built 2 containers - not connected
7. connected containers
8. opened one container and the transfer window
9. dropped one rock into the main container
10. dragged it to the connected container - it moved
11. dragged it back to the original container - it duplicated
12. dragged again from the connected container - freeze

to close game without signing off

1. alt tab to steam (should work - i did it with no other windows open, just steam and the game)
2. Ctrl Shift Escape to open task manager
3. note you will likely have np visible mouse
4. use tab till the Name column header is highlighted
5. use arrow keys to select SEVO
6. delete should end the process
7. if not then enter should expand the dropdown which will show the process selected - then hit delete


i hope this helps - love the game :-)

**Comment by tsunamayo** [comment] 2022-10-11 02:14
> It's a mining/collecting / storing issue... but I can't determine which one is causing the problem...
> 
> I've already asked other players to test and check what is happening. It seems a big problem, and more players must verify it.

Yeah I managed to reproduce the infinite collecting bug once, I see an error in the log that must happens when you look at some kind of invalid floating item, but I cant reproduce consistently or make sense of it. I will dig further (no pun intended)

**Comment by tsunamayo** [comment] 2022-10-11 02:30
@DrizztCode Hi, I fix an issue related to manual transfer the other day, I tried to reproduce your issue but it was fine.
Thanks!

**Comment by DrizztCode** [comment] 2022-10-11 09:57
@tsunamayo - thanks for the continued awesome work - really excited to try the new build :-)

**Comment by DrizztCode** [comment] 2022-10-11 19:27
i should note - i'm also having ingots multiplying (a few dozen suddenly becoming hundreds when moving through a conveyor system) - as well as the collector sucking items through solid objects - possibly due to giving them too high a velocity at some instant - but this is meaning even if i encase my belts with solid blocks - i still can't have my smelter setup behind but in range of the collector beam, since it sucks them through the belt etc

and of course all the disappearing inventory etc

i am sure that much of this will change with the new build - and so i am sure will all get a cleaner picture of what might still be going on once that's released - thanks :-)

**Comment by tsunamayo** [comment] 2022-10-20 01:14
@Uncle-Ulty Hi, I have fixed several issue explaining crashes and mystery corrupt items like we saw. Hopefully it is all fixed in 22w42a! Please tell me if it is not the case!

**Closed by tsunamayo** 2022-10-20 01:14 UTC
Labels: Bug
