### ISSUE TITLE
[Suggestion] Piloting QoL/Balance Recommendations

### ISSUE THREAD

**Issue by FlyingDebris** [tsunamayo/Starship-EVO#1906] opened 2020-04-30 05:37 UTC
Hi, Debby here with some general balance suggestions.

To keep it short and simple, I have three main suggestions, each with the goal of improving the general "flyability" of ships. I also have a few secondary suggestions, with the goal of fine tuning movement and improving quality of life for flying.

**Suggestion 1: General nerf of turn rates.**

This is fairly straightforward, many ships of all sizes currently border on "uncontrollable" as they turn far too quickly. Cutting turn rates in half or more would be a good way to test and fine tune it.

**Suggestion 2: Remove the circle in the middle of the screen where moving your cursor does not turn the ship.** 

This contributes to the "jerky" motion of ships right now, and removing it will also allow for much better control over one's ship, which is going to be a big factor as PvP gets near.

**Suggestion 3: General nerf of non-lightcruise speed.**

Currently, ships fly too fast to make PvP really practical, as it's far too easy to simply fly too fast to be hit. Slowing everything down (and more so for larger ships) will help people actually be able to fight.

**Secondary suggestions:**

_1: Allow limited movement in all directions._

This will allow players to further fine tune their movement, and allow quality of life things such as docking maneuvers to occur later on down the road.

_2: Increase charge time for lightcruise substantially._

In preparation for PvP, players need to not be able to simply jump out the moment a fight turns bad. Increasing the charge time for jumping, in conjunction with **Suggestion 3** will help this greatly.

Thank you for reading, and I'm looking forward to shooting your ships apart soon!

**Comment by Aiwii** [comment] 2020-04-30 05:41
THROTTLE! pleaseeee

**Comment by tsunamayo** [comment] 2020-04-30 05:46
Okay thanks for this contribution I will see if this trigger some debate I want to see other people reactor, I could indeed work on all point.
Regarding turning speed => I could balance it more of course but could people simply use less side thruster on their ship?
Thanks

**Comment by FlyingDebris** [comment] 2020-04-30 05:47
> Okay thanks for this contribution I will see if this trigger some debate I want to see other people reactor, I could indeed work on all point.
> Regarding turning speed => I could balance it more of course but could people simply use less side thruster on their ship?
> Thanks

At the moment I am testing with (visually at least) very few side thrusters. I think cutting the turn rate to a value (that may very well be too low) would be a good way to encourage debate and to find a sweet spot where it feels right.

**Comment by Dwarf-LordPangolin** [comment] 2020-04-30 07:10
> Suggestion 1: General nerf of turn rates.
> 
> This is fairly straightforward, many ships of all sizes currently border on "uncontrollable" as they turn far too quickly. Cutting turn rates in half or more would be a good way to test and fine tune it.

Agree. The thruster bricks are a great gameplay element, but they're a bit too powerful both in terms of turn rate and the speed they give. Only a small amount are needed to give big ships quite an impressive turn rate, and as Debris notes small ships get difficult to control very quickly. They could use a bit of a nerf.


> Suggestion 2: Remove the circle in the middle of the screen where moving your cursor does not turn the ship.
> 
> This contributes to the "jerky" motion of ships right now, and removing it will also allow for much better control over one's ship, which is going to be a big factor as PvP gets near.

Agree. I was hoping this one could be done by the player by fiddling with the controls under the deadzone setting for mouse. However, the deadzone setting is already at its minimum by default, still leaving the unresponsive circle Debris mentions.

To go with this, one thing that would be helpful is a way to reset the cursor to the center of the screen; that happens naturally when using a joystick, but most people don't play with one. So, a key to reset the cursor to the center of the screen would go well with removing the deadzone.


> Suggestion 3: General nerf of non-lightcruise speed.
> 
> Currently, ships fly too fast to make PvP really practical, as it's far too easy to simply fly too fast to be hit. Slowing everything down (and more so for larger ships) will help people actually be able to fight.

I _mostly_ agree with this; like, 95%. It's currently too easy to make ships that can fly at or near the upper limits of speed in SEVO. I agree that larger ships tend to be faster than they should; it's been a while since I compared ship speeds/ship masses, but the speed of large ships does not yet seem to decrease as quickly as it should when increasing mass. Small ships could stand a speed nerf, but not as strong a one as large ships.

I think two changes would achieve Debris' goal for this. I'd start by increasing the penalty to speed that mass provides. This should bring large ships' speed down by a bunch (so they feel the way large ships do in most games, it should be _hard_ to make a ship that's both big and fast), and smaller ships' by a bit. Second, in addition to reducing the turn rate provided by thrusters as Debris suggests in Suggestion 1 above, I'd suggest reducing the thrust they provide too; I think that would help with this problem too, especially with smaller ships, which end up getting a lot of speed from their thrusters.

I understand that part of the role of thruster bricks is to give smaller vehicles a viable means of propulsion that's not as bulky as the block engines, but ... well, let me put it this way: Zach was showing us a speeder bike that hit something like 415 m/sec. They're _probably_ faster than they need to be. ;)


> 1: Allow limited movement in all directions.
> 
> This will allow players to further fine tune their movement, and allow quality of life things such as docking maneuvers to occur later on down the road.

Agree. Speaking of fine-tuning movement, it would also be nice if the strafing + up/down controls worked to a reduced degree while in Boost, in the same way that real planes can use left and right rudder input to [drift to one side or the other while maintaining the same heading](https://i.insider.com/544a91a4ecad04c546a997a6?width=400&format=gif).


> 2: Increase charge time for lightcruise substantially.
> 
> In preparation for PvP, players need to not be able to simply jump out the moment a fight turns bad. Increasing the charge time for jumping, in conjunction with Suggestion 3 will help this greatly.

Agree. In addition, you might be planning this already, but: there needs to be a limitation on _where_ players can jump to lightcruise from (like in E:D, for example). ATM you can basically get in your ship, jump to lightcruise, and drop out at the destination. I would recommend starting with lightcruise being impossible if within 10 km of a station, ringworld, or planet, and impossible if within 2km of another ship; it might need to be raised or lowered from there, but that prevents players from being able to get away whenever things get too sticky.

**Comment by Battlepixel** [comment] 2020-04-30 08:09
1.) I also think that big ships are the problem.  
It looks stupid when large frigates have the similar turnrates like fighters. Small ships are okey. If you place to much thrusters your turn rate is very high but the control is also more difficult or to difficult^^(no advantage in pvp and pve) It would also look ugly to have to build small fighters with too many rotary thrusters. 
A cut would only be needed if people wanted to decorate their ships with an excessive number of thrusters without wanting to live with the consequence that control would then be very difficult. (but would have no negative aspects so okey)

3.)
For me it would be terrible to reduce the speed of the ship in general.

The following experiences from handling large drive blocks:

We have tried to accommodate as many drive blocks as possible in all fighter models (no brig thrusters give the forward thrust). None of the fighters can achieve a top speed of more than 250m / s when boosting and in combat, usually not even 150 m / s due to the inertia. The entire ship's energy is needed for the engines.
In the rather slow spaceshooter freelancer with similar speeds, all pvps take place at 200m / s in drift or with the afterburner held. These slow speeds are ok because in freelancers with afterburner you can accelerate from 0 to 200 / ms in about 1s (evasion is not a problem! 
In addition, the distances between objects are tiny and there are hyperspeed routes).
Starshipevo is more realistic there (evasion is difficult)
In Starshipevo, the space between ships and battles ranges from hundreds of meters to several kilometers. To slow down fighters would be very unepical and would drastically reduce the fun of flying (for me and some other friends of fast action). In our PVPs players and ai-controlled fighter planes of the same size can be hit well with turret-mounted weapons and sniperbarrels (no ai). But pvp takes to long.

The problem is, the current weapon system currently does not allow suitable weapons for space fighters. We see the problem here in the weapon system. Gattling cannons have too large a spread (it doesn't look good either) and it should also be possible to build even faster Gattlings (min 5Hz fire rate). In order to reduce the advantages of AI aiming, significant errors should be programmed in the AI ​​aiming.-> that's the only way to  to avoid Ai-aiming benefits and the exaggerated scatter of gattlings from de game.

In my opinion, large engine blocks could get even more thrust, so that you don't have to fill your entire fighter with it to reach just 200m / s in boost.

We never used brig-thruster for the forward thrust so I can't estimate if their thrust should be reduced.

**Comment by Sei-Neko** [comment] 2020-04-30 10:29
My 430m ship can currently turn sharper than most fighters I have. Is the turn rate calculated by the total number of brick thrusters located anywhere on the ship?

**Comment by ProPeach** [comment] 2020-04-30 13:14
I'm in the same boat as Debris and Pangolin.

**Side thrusters and speed** - At the moment it's far too easy to create a ship that is both fast *and* maneuverable, and that goes for any size. I strongly agree that there needs to be a much quicker drop-off in of top speed and agility as mass increase, right now equations are much too forgiving for large ships. It doesn't take too many brick thrusters to make them very agile and the heat produced by the small thrusters isn't enough to make them hurt for it.
As Debris says, ships are very "twitchy" and uncontrollable even with a very size thrusters, so cutting reducing their effect would help this too.
This illustrates the problem with brick thrusters being shared as both forward and side thrust, it's difficult to balance both at the same time. I really think that some diminishing returns in their ability to produce size thrust is needed, combined with the larger nerf to heavier ships. Perhaps this relationship would be better calculated using a ratio between side and forward facing thrusters.

**Deadzone** - This really needs some love too, it's damn near impossible to line up your ship accurately with this huge deadzone. It needs to be drastically reduced imo, with your rate of turn increasing the further away you move your mouse like in this example linked in #1749. I see that you've marked it as "To do", I'm excited to see your implementation!
https://imgur.com/XT7zyFQ
Additionally, currently if you move your mouse diagonally the ship will either yaw or pitch, but never both as you'd expect. This further contributes to the problem of controlling your ship accurately.

**Throttle** - As Aiwi mentions, throttle in boost mode is absolutely essential for flight in all kinds of situations.

I have a few blueprints that show the issues of speed and agility if you'd like to see them, but really the affects we talk about here can be seen on any ship by just placing more/less thrusters

**Comment by Battlepixel** [comment] 2020-04-30 14:23
I tested it out. If you build smallfighters full of  big thrusters(only the blockversion) like this one(9+2=11big thrusters): 
![Starship EVO_2020_04_30_16_09_49_406](https://user-images.githubusercontent.com/43222403/80720550-5ecbe080-8afd-11ea-8a0a-5cad316ab065.jpg)
you can reach 250 m/s in boost mode-> I think less speed despite building such a small ship full of thrusters would be no fun.

1) But if you compare the big thrusters you will notice that
brickthrust=6,4*blockthrust
If you would decrease brickoutput/Volume to blockoutput/Volume the speedproblem wil be solved

2) If you make agility and speed being not anymore a linear function of mass, but something like "speed and agility"=f(m)=a*m² or e^(m) or what you think would do best, the problem with big ships would also be solved

3) If you make a cruisedrive inhibition for the two cases that
- you got hit in the last 30 seconds
- enemy ships are in range
- you are in the gravityfield of the torus
also pvp-escape problem would be solved without senseless limitations



here two pics that compare thrust ouput
![Starship EVO_2020_04_30_16_02_39_956](https://user-images.githubusercontent.com/43222403/80721809-f4b43b00-8afe-11ea-961e-24363a28479c.jpg)

![Starship EVO_2020_04_30_16_03_05_533](https://user-images.githubusercontent.com/43222403/80721825-f978ef00-8afe-11ea-9840-3446009c63b7.jpg)

**Comment by FlyingDebris** [comment] 2020-04-30 17:02
> In relation to Suggestion 1.) "maneuverability"
> I also think that big ships are the problem.
> It looks stupid when large frigates have the similar turnrates like fighters. Small ships are okey. If you place to much thrusters your turn rate is very high but the control is also more difficult or to difficult^^(no advantage in pvp and pve) It would also look ugly to have to build small fighters with too many turn-thrusters.
> A cut would only be needed if people wanted to decorate their ships with an excessive number of thrusters without wanting to live with the consequence that control would then be very difficult. (but would have no negative aspects so okey)
> 
> In relation to Suggestion 3.) "Speed"
> For me it would be terrible to reduce the speed in general.
> 
> The following experiences from handling large drive blocks:
> 
> We have tried to accommodate as many drive blocks as possible in all fighter models (no brig thrusters give the forward thrust). None of the fighters can achieve a top speed of more than 250m / s when boosting and in combat, usually not even 150 m / s due to the inertia. The entire ship's energy is needed for the engines.
> In the rather slow spaceshooter freelancer with similar speeds, all pvps take place at 200m / s in drift or with the afterburner held. These slow speeds are ok because in freelancers with afterburner you can accelerate from 0 to 200 / ms in about 1s (evasion is not a problem!
> In addition, the distances between objects are tiny and there are hyperspeed routes).
> Starshipevo is more realistic there (evasion is difficult)-> Games with similar flightmechanics and skales as starshipevo have fighterspeeds between 200 and 550m/s with deactivated cruisedrive!! (X4 foundation)
> In Starshipevo, the space between ships and battles ranges from hundreds of meters to several kilometers. To slow down fighters would be very unepical and would drastically reduce the fun of flying (for me and some other friends of fast action->Flying through the asteroid field or past objects is only fun if you can be fast enough). In our PVPs players and ai-controlled fighters of the same size can be hit well with turret-mounted weapons with sniperbarrels (no ai). But pvp takes to long because of the slow rate of fire.
> 
> The problem is, the current weapon system currently does not allow suitable weapons for space fighters. We see the problem here in the weapon system. Gattling cannons have too large spread (it doesn't look good either) and it should also be possible to build even faster Gattlings (min 5Hz fire rate). In order to reduce the advantages of AI aiming, significant errors should be programmed in the AI ​​aiming.-> that's the only way to to avoid Ai-aiming benefits and the exaggerated scatter of gattlings from de game.
> 
> In my opinion, large engine blocks could get even more thrust, so that you don't have to fill your entire fighter with it to reach just 200m / s in boost.
> 
> We never used brig-thruster for the forward thrust so I can't estimate if their thrust should be reduced.
> 
> In relation to 2.) "lightcruise inhibation"
> 
> > Agree. In addition, you might be planning this already, but: there needs to be a limitation on _where_ players can jump to lightcruise from (like in E:D, for example). ATM you can basically get in your ship, jump to lightcruise, and drop out at the destination. I would recommend starting with lightcruise being impossible if within 10 km of a station, ringworld, or planet, and impossible if within 2km of another ship; it might need to be raised or lowered from there, but that prevents players from being able to get away whenever things get too sticky.
> 
> Lightspeed inhibation if an enemy ship is in range or you got hit in the last 30 seconds is a great suggestion that makes sense. But in my opinioin there has not to be any further limitation.
> 
> * consider that at 200m / s it is never possible to cross or explore the asteroid field.
> * Falling out of cruisedrive "between" the asteroids looks epic.
> * your star systems are large and this is greate, but 200 or 300m/s are far to less speed to explore such star systems, or objects like the ring-asteroid fields.-> we need lightcruise.
> * the possibility of smash if you use the lightcruise incorrectly makes the whole thing even more exciting.
>   ->If people want to collide with an object at light speed, you should not deny them that (But one day you have the time to implement, they should get destroyed when ramming with highspeed).
>   -> If people feel like flying into the empty space with the cruisedrive, they should be able to do so because it gives them the feeling of freedom to be able to travel to any point in the solar system.
>   An autopilot with which you can only spot certain positions and cannot reach the space in between would be terrible
>   -> senseless limitations never feel good

For the speed reduction, my main reason for recommending it is because as it stands spacecraft of all sizes go comically fast compared to everything else in the universe. And for reference, a lot of other games bump those numbers up to seem more "realistic" as they may be operating on different scales. EvE is a great example of this. I think you'll find that the vast majority of games don't have you actually moving at the speeds suggested by your speedometer.

**Comment by Battlepixel** [comment] 2020-05-01 10:47
> For the speed reduction, my main reason for recommending it is because as it stands spacecraft of all sizes go comically fast compared to everything else in the universe. And for reference, a lot of other games bump those numbers up to seem more "realistic" as they may be operating on different scales. EvE is a great example of this. I think you'll find that the vast majority of games don't have you actually moving at the speeds suggested by your speedometer.
> 
> EDIT: To expand on this, consider that your ship may be moving 250m/s as a baseline. Maybe 400m/s for a ship designed for PVP. This ship can be as short as 5-10 meters long. From the perspective of someone with a lot of time shooting stuff in blocky space games, you won't be hitting that ship, ever.

I think we are talking past each other (maybe because of my english)

argumentation:

The games I named show the speeds to scale.
- Freelancers (speeds in PVPs are even higher than those possible with blockthruster, even though the distances and objects in freelancers are much smaller)
- In X4 (carriers are several hundred meters long weapon ranges 2km [fighter] -8km [large ships]) you can race into a battle with 2km / s cruisdrive and 3km weapon range and bring a whole volley to the finish before rushing past the target . In Starshipevo, 400m / s is a problem, in our opinion due to the current weapon system, but I described that in my first post on the subject.

All hunters that we have built (without brick thruster for forward thrust) are built as light as possible and only stuffed with drives (blocks). None of the fighters manage 300m / s in a straight flight despite boost. We checked it again yesterday and with these optimized (without brick thruster) space fighters in pvp we usually do not exceed 100m / s because we change our speed vector too often (for 250m / s the fighters need 15-20s just out of boost). Hitting the enemy at these speeds was no problem for us with sniperbarrels) Regardless of the design, the combat fighters without brick thruster cannot be built significantly faster with this small size and will never reach 200m / s in pvp. Even if we kicked out the landinggeare and removed all the deco, that wouldn't change anything significantly.


Key/main points:
I)
 I would like to make it clear that in our **opinion** the current thrust of the truster blocks, which is 6.4 times smaller by volume than that of the bricks, is even very tight and should under no circumstances be reduced, because otherwise flying is no longer fun. We also find that the brick thrusters have an excessive amount of thrust, but because you can build with them so nicely only the thrust should be adjusted, but not the thruster removed.

II) 
If you do not agree with me that 100m / s (because of the turns) in battle is not low enough, then your reason for this is probably the difficulty in aiming with the current weapon solutions. As I have described, the worst solution is to fix the problem by making everything slower and less action-packed. **The better solution** would be to adapt the weapon system!!!! As already mentioned, e.g. X4 is a good example. Alternatively, you can also choose "Voiddestroyer 2" as an example.

**Comment by Battlepixel** [comment] 2020-05-01 10:59
If you have problems with balancing or other game aspects, it would be nice if you thought carefully beforehand which solution to this problem has the least disadvantages and influences on other game aspects and is still easy to implement for the dev. But if you really just find it nicer when everything is slower, then this is a wrong assumption that I am sorry for. Then I'm just of a different opinion and think that a space fighter shouldn't move at the same speed as a car in city traffic ^^. But as I said, it's just an opinion.

**Comment by FlyingDebris** [comment] 2020-05-01 15:54
> If you have problems with balancing or other game aspects, it would be nice if you thought carefully beforehand which solution to this problem has the least disadvantages and influences on other game aspects and is still easy to implement for the dev. But if you really just find it nicer when everything is slower, then this is a wrong assumption that I am sorry for. Then I'm just of a different opinion If I think that a space fighter shouldn't move at the same speed as my old skoda Fabia^^. But as I said, it's just an opinion.

I think your issue may stem from a lack of PvP experience. A lot of what you've been describing has been PvE, where you will likely not notice how annoying it would be from the other side.

To that end, I'd like to extend an offer to do some ingame testing so that I may illustrate my point to you.

**Comment by Battlepixel** [comment] 2020-05-01 18:42
> I assure you, you're not going to have an easy (or fun) time hitting a 25 meter long object moving at 250m/s,
in any case,^^ but we should not further discuss that here
we can test it like you say
> To that end, I'd like to extend an offer to do some ingame testing so that I may illustrate my point to you.
.. and I could too, so good idea
Under what name can I contact you on Steam and/or discord?
but consider my spoken English is far worse than that of the googel translator.

**Comment by FlyingDebris** [comment] 2020-05-02 02:01
> > I assure you, you're not going to have an easy (or fun) time hitting a 25 meter long object moving at 250m/s,
> 
> in any case,^^ please note/ dont ignore my key messages. Problems are caused by the current weapon system. So why do you want to choose the bad solution and make the speeds lower than 360km / h in combat (#turning) and and therefore significantly lower than in the good working spacegames I mentioned, with have similar skales, if you can also adapt the weapon system?
> but we should not further discuss that here and spam,
> if you can't invalidate that argument/give a good reason(dont know how to write in english)
> we can also test it like you say or discuss/write on discord
> so as not to flood with posts that contain no new arguments
> 
> > To that end, I'd like to extend an offer to do some ingame testing so that I may illustrate my point to you.
> 
> .. and I could too, so good idea
> Under what name can I contact you on Steam and/or discord?
> but consider my spoken English is far worse than that of the googel translator.^^

On Discord I'm FlyingDebris#1109, you can find me in the official discord.

**Comment by tsunamayo** [comment] 2020-05-02 07:10
Okay thanks for the discussion!
For now regarding the heated debate on speed:
=> I will implement the deadzone, the lead indicator and the builtin gimbal. This should make things much better!
=> then we will see if we need to nerf speed. I have no problem to nerf speed for the sake of gameplay. I dont really see why higher speed would be much fun if you cant hit anything. But we will need to test first.

Then for thruster / turn rate: 
yes thruster are "realistic", they add the same thrust whatever your ship mass. Then from the total thrust and total mass I compute the thrust to weight, then I use that thrust to weight to get "unrealistic" force applied to the ship. 
=>My initial plant for nerf agility for large ship was to have side thruster only for the smaller one, who are heat ineficient. I feel I havent seen enough big ship fully fitted to see if that system is enough or not... Of course an big empty shell with no system is gonna be super light and agile... If you have some big ship as reference to send my way so I can judge please do!
=>If that is not enough I will take into account the mass of the ship on top of the thrust to weight (I will likely do it, but I want to see some data first, aka ships ;)...)
=> also yes I will reduce the max turn rate for super high Thrust to Weight ship. If you have some references to send me go ahead! But again why people just dont put less thrusters ;)

Escape with lightcruise:
=> yes this is a must do, question is on which form? I want to make escape a component of the gameplay. I could explore that in many ways: if the ship thruster are damaged enough, no jump possible. Or have a block that to prevent enemy from jumping (either passively or via player activation). Also I could add a cooldown on the thrusters before the next jump. I also want to player to be able to "follow" the ennemy ship if he choose to. I could do all of the above! I feel this warrant a dedicated brainstorming session.

**Comment by Battlepixel** [comment] 2020-05-02 09:48
[Horus v54(70%of full mass, 100% thrust&energy&shields).zip](https://github.com/tsunamayo/Starship-EVO/files/4567429/Horus.v54.70.of.full.mass.100.thrust.energy.shields.zip)


In the worst case, the ship has 70% of the final mass, but otherwise has all the system blocks it will have when it is finished. In the originally planned design, twice as many side thrusters were provided, but regardless of this, it should give a good impression that large ships are too maneuverable

**Comment by Battlepixel** [comment] 2020-05-05 16:50
The communication between us was..hmm suboptimal ^^ but we could at least exchange ideas about where our points of view differ.

We both think: 
- Brickthrusters and Brickreactors are generally OPs compared to blocksystems
- Large ships are too fast and agile
- the top speeds in generally are okey
- the average acceleration of 220m/s in 20s of this shipexample full of thruster and only the reactors 
![Starship EVO_2020_05_05_17_55_02_612](https://user-images.githubusercontent.com/43222403/81092006-48a89080-8f00-11ea-8903-e8627903f5c0.jpg)
is poor enough 

Only I think: 
-If you can not get much more acceleration without bricks and this ist not much  like we **both** agree, it makes no sense to decrease the Big-blog-output too, because on this way it stays unbalanced.  On this point our communication failed

**Comment by nukeguard** [comment] 2020-08-28 04:40
> Okay thanks for this contribution I will see if this trigger some debate I want to see other people reactor, I could indeed work on all point.
> Regarding turning speed => I could balance it more of course but could people simply use less side thruster on their ship?
> Thanks

Is the ship turn speed based on ship weight/scale/shape? eg. the heavier the ship the slower it's turn

**Closed** 2022-11-08 04:05 UTC
Labels: Suggestion
