### ISSUE TITLE
Handheld bugs

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#4719] opened 2022-05-27 17:48 UTC
1/8 scale Decals on handheld builds have some sort of visual bug:
![20220527194236_1](https://user-images.githubusercontent.com/81495956/170763445-0276e47c-3f39-4354-a6e6-d6b3150c9e33.jpg)
![20220527194253_1](https://user-images.githubusercontent.com/81495956/170763456-ce3090a9-23b4-47ab-bd50-d927cba1a5dc.jpg)
[Hand Mining Tool.zip](https://github.com/tsunamayo/Starship-EVO/files/8788815/Hand.Mining.Tool.zip)

Placeing a second handle on a handheld ends with this:
To reproduce:
place a handle on top of another handle.
![20220527194523_1](https://user-images.githubusercontent.com/81495956/170763731-b390f356-38f3-4e89-b708-edf58a7c0709.jpg)

![20220527193444_1](https://user-images.githubusercontent.com/81495956/170763571-55ebfc33-8d58-433c-8c7d-210407b1a27e.jpg)

**Comment by tsunamayo** [comment] 2022-06-15 23:43
@BigBadKangaroo Hi, so the first issue should be fixed (not 100% sure, I cant reproduce it but I fixed something that could explain it). The second issue is also fixed, for 22w24a. Thanks!

**Closed by tsunamayo** 2022-06-15 23:43 UTC
Labels: Bug
