### ISSUE TITLE
[19w28a] Minimizing HUD with F2 can stall HYP jumps

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1350] opened 2019-07-13 03:48 UTC
### Short Description of the issue:
If a destination is set for the autopilot, but F2 is pressed to minimize the HUD while the jump drive is charging up, this can delay the jump until the HUD is restored with F2 and the jump can start over again.

### Steps to reproduce the issue:
Select a destination for the autopilot, then press F2 to hide the reticule while the jump is charging up. The more the drive is allowed to charge, the less likely this is to interrupt it, so the bug is best reproduced by pressing F2 immediately after you see the charging meter begin to fill up.

### Environment
- Skywanderers version: 19w28a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3388411/output_log.txt)

**Comment by ZachZent** [comment] 2019-07-13 05:30
To add to this when you exit supercruise, the ship will come to a complete stop rather then continue to fly normally. A bit of an odd gap

**Comment by tsunamayo** [comment] 2020-06-16 01:12
I think this should be fixed in latest versions, I was not able to reproduce. Ping me if I am wrong! Cheers

**Closed by tsunamayo** 2020-06-16 01:12 UTC
Labels: Bug
