### ISSUE TITLE
mechanism crashes the game

### ISSUE THREAD

**Issue by Azathoh-the-blind-idiot-god** [tsunamayo/Starship-EVO#5390] opened 2023-12-13 19:59 UTC
### Short Description of the issue:

I have created a folding heat sink consisting of ~20 folding panels on 2 hinges each. activating all these hinges at once crashes the game.
Currently just activating the mechanism crashes the game but sometimes it take some minor spamming to cause a crash.

### Steps to reproduce the issue:

spawn the included blueprint.
repeatedly use the switch.

### Environment
- Starship EVO version: 23w41a
- Graphics Card: RX5700

### Additional information:

[electric greeble cubes.zip](https://github.com/tsunamayo/Starship-EVO/files/13665084/electric.greeble.cubes.zip)
[Azathoth frigate 2 (23w41a).zip](https://github.com/tsunamayo/Starship-EVO/files/13665091/Azathoth.frigate.2.23w41a.zip)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/13665098/Player-prev.log)

**Comment by tsunamayo** [comment] 2023-12-14 01:09
@Azathoh-the-blind-idiot-god Hi, I cant reproduce the crash but I see some weird error that I suspect are linked to sfx. I keep you posted.

**Comment by tsunamayo** [comment] 2023-12-14 02:19
@Azathoh-the-blind-idiot-god Hi, this should be fixed for next build. Thanks!

**Closed by tsunamayo** 2023-12-14 02:19 UTC
Labels: Bug
