### ISSUE TITLE
AND Gates and Timers

### ISSUE THREAD

**Issue by FantasyDragon14** [tsunamayo/Starship-EVO#2980] opened 2020-09-18 13:22 UTC
### Short Description of the issue:

AND-Gates do not activate if both inputs are Timers with the same delay(that are both activated simultanuisly)

### Steps to reproduce the issue:

try to activate an AND-Gate with 2 Timers

### Environment
- Starship EVO version: 20w37a
- Graphics Card: 

### Additional information:

Screenshot:
![20200918150356_1](https://user-images.githubusercontent.com/52784423/93602082-6879b600-f9c2-11ea-9252-6c5fbfe7e5e1.jpg)

Log:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5245756/output_log.txt)

**Comment by tsunamayo** [comment] 2020-09-20 02:43
Hi, I see. Is this kind of contraption really useful? Thanks

**Comment by matejkar** [comment] 2020-09-20 07:11
@tsunamayo lol, i think people got bored of the minumum building requirements and decided to go play with gates cuz why not

**Comment by AlienXtream** [comment] 2020-09-20 10:42
would i be correct in guessing this is something to do with active duration and update order?

**Comment by talrey** [comment] 2020-09-20 15:39
It's caused by the "logic bomb prevention" patch from a while back, which kills and drops any further signals in a frame after the first one arrives. That is:
1. Switch is turned On. Both Timers start running.
2. Both Timers complete in the same frame.
3. First Timer emits a signal to the AND gate, which reevaluates itself.
4. Second Timer emits a signal to the AND gate, but this signal is dropped without evaluation.
5. AND gate remains Off.
6. Second Timer is now "invalid", because it thinks it sent an On signal but the AND gate thinks it's still Off.

**Comment by talrey** [comment] 2020-09-20 15:44
As for people using this stuff, yes! I see it catching people out on the Discord now and then, when they're trying to make fancy landing gear or the like. We have such an elegant, powerful logic gate system in this game and this issue absolutely cripples the cool stuff people could be making with it.

**Comment by WILDCATreactor** [comment] 2020-09-21 09:07
potential workaround: timers go to switches which then feed into the AND gate, your initiator is gonna have to be a button instead of a switch though, to retain a simple on/off function

**Comment by Gliese-832-c** [comment] 2020-09-21 16:17
Oops, I reported a similar issue, but didn't see this one. Yes, I agree with @talrey. We have such an awesome logic gate system, and the logic bomb prevention patch absolutely cripples it, like @talrey said. I understand wanting to prevent lag, but why not make the amount of simultaenous signals be configurable? The default could be 3 or so, and it could go from 1 to infinite in the settings. I'm ok with making the game accesible and providing new players with a stable experience, but you shouldn't limit more high-end players who are willing to go further!

**Comment by talrey** [comment] 2020-09-22 02:12
Making it configurable will result in blueprints breaking when they're shared to people with a lower setting.

**Comment by Gliese-832-c** [comment] 2020-09-22 16:32
Hmm. Maybe the default/minimum could be set to 3? That should satisfy a majority of builds. And for those, that use more than 3, make the game display a big red warning when spawning the ship in.

**Comment by tsunamayo** [comment] 2020-09-28 08:01
I see. It would need a deeper logic refactoring to address.
@talrey would adding a single frame delay between each other gate notification break your stuff? Do you need it to be instant?
I could always increase the limit, but it will always break at one point.
Cheers

**Comment by Gliese-832-c** [comment] 2020-09-30 14:09
I suggest closing this issue, because the discussion was moved to https://github.com/tsunamayo/Starship-EVO/issues/2983.

**Comment by tsunamayo** [comment] 2020-10-05 04:31
@FantasyDragon14 @talrey Issue finally fixed for 20w41a. Thanks all!

**Closed by tsunamayo** 2020-10-05 04:31 UTC
Labels: Bug
