### ISSUE TITLE
No image on the logic blocks

### ISSUE THREAD

**Issue by RichardGilmore** [tsunamayo/Starship-EVO#2923] opened 2020-09-07 22:56 UTC
Ship computers and Logic blocks dont have images of what they are on them. For example, my AND blocks dont have the AND symbol on them, they are just blue.

...

### Steps to reproduce the issue: No steps. It was this way when I first installed the game. I didnt know logic blocks were supposed to have pictures until I saw a picture of other peoples logic blocks on youtube.

...

### Environment
- Starship EVO version: 20W35A
- Graphics Card: GeForce 660 GTX 660

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5185227/output_log.txt)

**Comment by tsunamayo** [comment] 2020-09-08 00:58
Hi, could you tell me if you see shadows and other transparent blocks? Thanks

**Comment by RichardGilmore** [comment] 2020-09-08 01:17
HI! I really love the game, btw! I dont see any transparent blocks. I do see the player shadow.

**Comment by tsunamayo** [comment] 2020-09-08 01:37
So the issue is fixed in 20w36a, I have just updated the default build to this version, so if you reload steam you will see the fix. Thanks ;)

**Closed by tsunamayo** 2020-09-08 01:37 UTC
Labels: Bug

**Comment by RichardGilmore** [comment] 2020-09-08 02:15
Merci! It looks fantastic! Thanks very much!
