### ISSUE TITLE
game lag after spawning a ship 

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#3288] opened 2020-11-24 22:03 UTC
### Short Description of the issue:
i wanted to spawn a ship and it didn't load in after that my game started to really lag hard, i tried reloading the world, making a new world, reinstalling the game, restarting my laptop to ge rid of it but its still lagging a lot. 
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 20w48a
- Graphics Card: 

### Additional information:
the ship used was drake caterpillar  
https://steamcommunity.com/sharedfiles/filedetails/?id=2267331012

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5592996/output_log.txt)

**Comment by KINGrimson** [comment] 2020-11-24 22:38
update: i got my problem fixed by verifying integrity of the game, after i did that the game run back normal

**Comment by tsunamayo** [comment] 2020-11-24 23:23
@KINGrimson I see, and you are now able to spawn the ship normally? Thanks

**Comment by KINGrimson** [comment] 2020-11-24 23:32
@tsunamayo i havent tried yet, bit scared to try again, i dont want it to happen again, and it was a very complex ship i tried to spawn soo yeah

**Comment by tsunamayo** [comment] 2020-11-25 01:15
I can spawn this ship without issue. What is your CPU - RAM? Thanks

**Comment by KINGrimson** [comment] 2020-11-25 05:49
i have a intel(R) core(TM) i5-9300h CPU @2.40GHz 2.40GHz
and my ram is 16G

**Comment by tsunamayo** [comment] 2020-11-25 05:56
It is weird, I dont see any issue in the log, this ship should spawn just fine. It is definitely hyper detailed and make my PC lag a bit, but at least it shows up.

**Comment by KINGrimson** [comment] 2020-11-25 06:01
yeah i dont know what happend to my side to cause that, its a weird issue that i dont know what cause it,

**Comment by tsunamayo** [comment] 2020-11-26 05:13
Okay so for now as we are not able to reproduce and this was fixed I will close it. Dont hesitate to ping me if it happens again / often. Thanks!

**Closed by tsunamayo** 2020-11-26 05:13 UTC
Labels: Bug

**Comment by KINGrimson** [comment] 2020-11-26 08:34
sure no problem i will
