### ISSUE TITLE
Can't Change Ship Flight Down Hot Key.

### ISSUE THREAD

**Issue by Thasrion** [tsunamayo/Starship-EVO#2161] opened 2020-05-23 23:31 UTC
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4672682/output_log.txt)
### Short Description of the issue: Changing Hot key for Ship Flight. When attempting to alter the Down key to C I get the following >< and it doesn't save. I'm unable to change the Hot Key.

...

### Steps to reproduce the issue: Click on the field to change the key to another keyboard key. Changes to >< and doesn't allow me to change it. The Down doesn't work in game.

...

### Environment
- Starship EVO version: 20w21c
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
Before: https://media.discordapp.net/attachments/334015418710622208/713895902049206322/unknown.png
After: https://media.discordapp.net/attachments/334015418710622208/713895856608116806/unknown.png
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4672681/output_log.txt)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment] 2020-05-23 23:42
Do you cant change it for any key? Or do you try to assign it to a given key? Also I will need your keyboard region and system local, it might be a keyboard is game is having trouble with. Thanks!

**Comment by Thasrion** [comment] 2020-05-24 02:32
I In the US, key board is a Corsair STRAFE Gaming Keyboard. I was able to change the Character movement when using ZeroG mode to C for Down but not the ship down key.

**Comment by tsunamayo** [comment] 2020-05-24 04:10
Could you send me your output.log file? I cant reproduce it works fine for me, I will need your log to investigate. Thanks!

**Comment by Thasrion** [comment] 2020-05-24 13:59
I attempted to send it when I created the tread. here I'll try again.
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4673648/output_log.txt)

**Comment by Thasrion** [comment] 2020-05-24 14:00
It worked this time.

**Comment by tsunamayo** [comment] 2020-05-26 04:01
okay, the first this issue arose you are positive you only clicked on C, not something else? Or you dont remember?

**Comment by Thasrion** [comment] 2020-05-26 12:16
Yes, first key change was the C key for sure.

**Closed** 2022-11-07 07:48 UTC
Labels: Bug
