### ISSUE TITLE
Hovercraft at end of Tutorial bit buggy

### ISSUE THREAD

**Issue by ThatFungiNub** [tsunamayo/Starship-EVO#2085] opened 2020-05-16 14:42 UTC
### Short Description of the issue: 
Entering the default hovercraft at the end of the tutorial and activate the yoke makes the screen go funky colours.

...

### Steps to reproduce the issue:
Activate the yoke on the default hovercraft in tutorial 

...

### Environment
- Starship EVO version: 20w20d
- Graphics Card: GTX 970

### Additional information:

![](https://cdn.discordapp.com/attachments/453933461577793536/711224349520166972/unknown.png)

![](https://cdn.discordapp.com/attachments/453933461577793536/711225854243504249/unknown.png)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4638546/output_log.txt)

**Comment by Garrett-C** [comment] 2020-05-16 15:50
You sure you didn't eat any of the mushrooms in the codex?

**Comment by JRL101** [comment] 2020-05-16 17:41
LMAO I'll say! 
![image](https://user-images.githubusercontent.com/33255536/82126470-931eec80-97df-11ea-9616-10c22ef760b6.png)

**Comment by JRL101** [comment] 2020-05-16 17:42
LMAO okay reloading the game changed my version to "CACA" and im in space 
![image](https://user-images.githubusercontent.com/33255536/82126485-b0ec5180-97df-11ea-954f-1f2680d749b1.png)

**Comment by SageThe13th** [comment] 2020-05-16 22:45
I had this problem with one of my old hovercraft made before 20w20c. You can fix it by removing the hovercraft core and replacing it.

**Comment by tsunamayo** [comment] 2020-05-16 22:55
@JRL101 was it after your re-install or before?
Yes I need to refresh that hovercraft as the setting is not valid since the hovercraft update. I will also make sure that:
1) you cant input invalid setting
2)  an invalid setting wont make the game crash...

**Comment by tsunamayo** [comment] 2020-05-17 00:22
@Garrett-C Can you tell me if you can reproduce this on a fresh character too?
I cant reproduce any of the bug people have been throwing at me lately, god this is so frustrating...

**Comment by Garrett-C** [comment] 2020-05-17 00:35
@tsunamayo Just made a character and have not been able to reproduce the bug

**Comment by Garrett-C** [comment] 2020-05-17 00:35
oh wait
![image](https://user-images.githubusercontent.com/43644633/82133044-bdbc7580-97de-11ea-9426-616834b7af58.png)

**Comment by tsunamayo** [comment] 2020-05-17 00:42
ah okay you need to wait a bit!

**Comment by tsunamayo** [comment] 2020-05-17 00:43
still cant reproduce...

**Comment by tsunamayo** [comment] 2020-05-17 00:46
Are you guys in 3rd person or 1st person?
are you using the game in windowed mode or else?
Thanks

**Comment by ThatFungiNub** [comment] 2020-05-17 00:53
First person, full screen for me personally. It doesn't happen right away and it's only on the default spawned hovercraft

**Comment by tsunamayo** [comment] 2020-05-17 00:53
I just managed to reproduce the bug in windowed mode...

**Comment by tsunamayo** [comment] 2020-05-17 01:17
Okay I cant reproduce this in the new version, same save same condition. Issue seemed fixed in 20w20e (I have been working on player parenting recently). Not 100% sure though, so I will leave that open and you will tell me in next patch if that fixed it. Thanks!

**Comment by tsunamayo** [comment] 2020-05-18 03:42
Okay guys tell me if you still see the bug in 20w21a! Thanks

**Comment by Majikmonster** [comment] 2020-05-18 11:25
I still get the bug. This time on a brand new hovercraft and not the starter one.
![20200518071643_1](https://user-images.githubusercontent.com/51390907/82207960-b083b180-98d8-11ea-9650-f350ec8e362f.jpg)
![20200518071611_1](https://user-images.githubusercontent.com/51390907/82207962-b083b180-98d8-11ea-8793-d84c6e0a7eb5.jpg)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4643780/output_log.txt)

**Comment by JRL101** [comment] 2020-05-18 20:04
> 
> 
> @JRL101 was it after your re-install or before?
> Yes I need to refresh that hovercraft as the setting is not valid since the hovercraft update. I will also make sure that:
> 
>     1. you cant input invalid setting
> 
>     2. an invalid setting wont make the game crash...
>        Keep you guys posted

AFTER a reinstall, it was re-creatable on a new character or old one, only way to do it was activating the controls, i think sitting in the seat was fine. Reloading back in (after exit game), i was in space at a random location.

Seems similar to where i was teleported to after my ship exploded and voided me. But with the hover craft i could see the galaxy after the reload,.

**Comment by JRL101** [comment] 2020-05-18 20:17
@Majikmonster Is this still happening in **`20w21a`** ?

**Comment by JRL101** [comment] 2020-05-18 20:50
Well seems like replacing the ships repulsors cause the same bug. but this time it crashed my game :|

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4646598/output_log.txt)
`
%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Characters`
[JRL101-2.zip](https://github.com/tsunamayo/Starship-EVO/files/4646600/JRL101-2.zip)

**Comment by JRL101** [comment] 2020-05-18 23:48
Cant replicate it. Been messing with this over and over but its gone after reloading. so weird. 
Suspected save corruprion, due to version switch.

**Comment by tsunamayo** [comment] 2020-05-24 01:16
@JRL101 @Majikmonster this issue should have been fixed for 20w21b. Thanks!

**Closed by tsunamayo** 2020-05-24 01:16 UTC
Labels: Bug
