### ISSUE TITLE
Invisible Blocks

### ISSUE THREAD

**Issue by Misteropie** [tsunamayo/Starship-EVO#3408] opened 2020-12-26 22:26 UTC
### Short Description of the issue:

Occasionally blocks placed will be invisible

### Steps to reproduce the issue:

1. Open game
2. Load save
3. Start a new grid (with starter block)
4. Placed block

### Environment
- Starship EVO version: 20w49a
- Graphics Card: Nvidia GeForce RTX 3080

### Additional information:

It is safe to say that 99.999% of all my builds use mirror mode so I also came across something interesting with this bug. Sometimes when placing a block they would both be invisible and other times only one will be. It is not always the one I place but can sometimes be the mirrored block as well. I normally build in heavily build populated worlds so when reproducing in other files it might help to populate them.

Please also include the `output_log.txt` file. You can find your log here: 
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5743713/output_log.txt)

**Comment by Regnion** [comment] 2021-01-03 06:24
This is an issue for me as well. Simply start building a ship, and blocks will be invisible. You can be in a fresh new world, mirrored mode or not, blocks are simply invisible. Restarting the game will make most reappear, but not all of them. It's also not reasonable to constantly restart your game just to see what you're building.

**Comment by tsunamayo** [comment] 2021-01-05 05:20
@Regnion Hi, I agree, but I need a test case so I can reproduce and fix the bug. If you are reproducing often maybe you could explain me how you do! Thanks

**Comment by tsunamayo** [comment] 2021-01-08 05:17
@Regnion If you have a save where you are have invisible block even after reload, could you upload it here? I am having trouble to get a clear reproductible test case of what is happening. Thanks

**Comment by Regnion** [comment] 2021-01-08 05:25
@tsunamayo No. The invisible blocks do not persist after reload. I've found that spawning and despawning a couple ships generally leads to blocks becoming invisible. Restarting the game fixes the issue.

**Comment by tsunamayo** [comment] 2021-01-08 05:35
@Regnion okay good to know, I will try to spawn and unspawn. Couple question: do you have a lot of entity in your world? Also do you noticed it was linked to deleting stuff? Thanks

**Comment by Regnion** [comment] 2021-01-08 18:36
@tsunamayo No, no additional entities or adjustments to the existing ones. I try to keep a "blank map" to keep things simple and avoid potential errors. I think it's linked to the despawning of ships specifically, that results in blocks beginning to disappear on other ships. I only notice this when I'm looking at someone's workshop creation, despawn it, and resume building. That's when I encounter the issues.

**Comment by schlid** [comment] 2021-01-15 00:36
I also have been experiencing this. New save, new character, no additional entities in the world. Inconsistently every 3rd block placed on average will be a ghost block. I've reinstalled the game, completely deleted local content between the install and this still occurs for me.

**Comment by tsunamayo** [comment] 2021-01-15 01:08
@schlid this is pretty bad. Could you send me your character save? Cheers

**Comment by schlid** [comment] 2021-01-15 01:14
[schild.zip](https://github.com/tsunamayo/Starship-EVO/files/5817799/schild.zip)
Attached the character file - if this is what you mean. I took a break because of studies and the file structure has changed a lot since I looked last. Also included the various log files seperately.

**Comment by tsunamayo** [comment] 2021-01-15 01:20
@schlid Thanks mate, I hope you are doing good! I keep you posted, I really would like to fix that issue but I cant seems to reproduce well.

**Comment by schlid** [comment] 2021-01-15 01:23
@tsunamayo I'm doing well cheers. If you need me to stream how I'm building to make the blocks appear lmk, I'd really like to get building again soon ^^

**Comment by tsunamayo** [comment] 2021-01-15 03:41
@schlid thx, let me try to see if I can reproduce first!

**Comment by tsunamayo** [comment] 2021-01-15 03:45
@schlid I cant reproduce, if you can show me how it happen on your side? What is your PC spec?

**Comment by schlid** [comment] 2021-01-15 05:37
> @schlid I cant reproduce, if you can show me how it happen on your side? What is your PC spec?

I just switched my Pc off but I'll record what happens tomorrow and send specs

**Comment by schlid** [comment] 2021-01-15 16:13
Just went to record - I look a bit silly now as I was placing blocks for 5 minutes or so and none appeared as ghost blocks.
Regardless here are my pc specs.
i7-4790k
16GB DDR3 2133MHz
Nvidia RTX 2060
Game is stored on my SSD

**Comment by Regnion** [comment] 2021-01-17 06:21
Actually I made some handhelds earlier.The item stands have a habit of vanishing, especially if you place a handheld and then unspawn it, place another one, unspawn it, then you might see blocks becoming invisible. But it's not something easily reproduced, moreso that you stumble upon it while building.

**Comment by BE-Arbiter** [comment] 2021-03-04 17:22
Had the same issue, start the game then I have the problem.
i7-9XXX
24Gb DDR4 Ram
GTX 1660 Super
Stored on SSD

**Comment by Dauby** [comment] 2021-03-14 21:24
I am also having the issues, new game and the blocks go invisible, but not all of them, really annoying and I have to keep deleting the blocks and replace them to not have them

**Comment by tsunamayo** [comment] 2021-12-07 04:57
@Regnion Hi, as I know you had built a bit recently did you had any Invisible block issue again (engine changed quite a bit). Thanks

**Comment by tsunamayo** [comment] 2021-12-09 04:58
Okay I am gonna close it, please ping me if you guys see that again!

**Closed by tsunamayo** 2021-12-09 04:58 UTC
Labels: Bug
