### ISSUE TITLE
[Bug] Ships and planets flash violently when contacting planetary water

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5463] opened 2024-02-08 02:07 UTC
### Short Description of the issue:
Upon certain triggers near (planetary) water, the ship will flicker rapidly. If you are piloting the ship, then everything will flicker rapidly until you leave your seat. The planet, every other planet, and the system's primary star may disappear.

We suspect it may have to do with CE's and mechanisms in planetary water.

When you exit the game and reload the world, sometimes the ship will be back to normal, and sometimes the ship will be removed from the world entirely. We are unsure of the percentage chance or the exact conditions.

Please see the attached video. Tested in Creative mode. We have not tested on ringworlds.

There are a few things that can trigger the issue. We're not yet sure whether they'll 100% trigger the issue. I've been running into unexpected triggers while trying to reproduce suspected ones.

### Steps to reproduce the issue:
Fly a ship near water (with a starter block so it holds its position when you leave it), then hover above it. (If it accidentally enters water at this point, it will behave normally. This part is just setting up.)

Now, do one of the following:
1. Activate a mechanism such that a part of the ship enters the water because of the mechanism. Pistons and hinges were tested so far.
2. Fly lower until a part of the ship is submerged, leave your ship, then attempt to add/remove blocks from the ship.
3. Fly lower to submerge a fuel scoop connected to an electrolyzer and fuel tank. Observe the electrolyzer generating fuel for the fuel tanks. Then, delete one of the pipes in the chain.

### Environment
- Starship EVO version: 24w05a
- Graphics Card: 1070TI, however another player had experienced the same issue, and it appears to be triggered by an event. There's no flickering prior to this trigger.

### Additional information:
https://github.com/tsunamayo/Starship-EVO/assets/10069469/eef78a92-b21c-4784-b770-f16971ab995a

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14203439/Player.log)

**Comment by asanagisae** [comment] 2024-02-08 02:17
In the world above, when I reloaded the game, the ship cannot be interacted with. I can't build on it, and I fly through it without no-clip (F5). I can't see any of the planets or the system's star from where I am.

If I open the codex, and click the teleport tab, then click the teleport tab again, all options disappear.
![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/f28758eb-a750-469e-b07c-d0d2eee2b2d7)

If I go to any other tab, _then_ click the teleport tab, I'm able to go to the other ships in the system, and the game seems mostly normal.

**Comment by tsunamayo** [comment] 2024-02-08 02:45
@asanagisae Hi, thanks, as it seems ship related could you send me your blueprint? Thanks

**Comment by asanagisae** [comment] 2024-02-08 02:59
I opened an issue because another player was reporting it, but they had some difficulty with the video recording software. It's _probably_ not ship specific, but perhaps there's some unknown requirements here.

This is the ship I used in the video above. Press "2" (while in the pilot seat) near the water to open the wings and reproduce the bug. Press "1" to close the wings.

[Tumbler v2.zip](https://github.com/tsunamayo/Starship-EVO/files/14203756/Tumbler.v2.zip)

**Comment by Huttrem** [comment] 2024-02-08 03:04
https://github.com/tsunamayo/Starship-EVO/assets/159193324/4ba7dc28-4b2e-42cf-837a-e95e448b97c8

hi im the other player, and i got the problem with two ship's now, is trigger went scoop is added aparently

**Comment by Huttrem** [comment] 2024-02-08 03:17
the ship's are like in two dimension, btw the trees vanish went i mine them

https://github.com/tsunamayo/Starship-EVO/assets/159193324/d62cda8d-74e7-4b41-87c6-753cfff119be

**Comment by tsunamayo** [comment] 2024-02-13 00:03
@asanagisae Hi, I think the issue is related to low FPS resulting from on of your action like deleting a brick and so on.
I update the physics engine with a feature that should prevent that, fix will be in 24w07a. Cheers

**Closed by tsunamayo** 2024-02-13 00:03 UTC
Labels: Bug

**Comment by Huttrem** [comment] 2024-02-13 00:32
@tsunamayo i was the one who found this issue went building an extendible scoop to get water, wish it work's, thanks
