### ISSUE TITLE
[BUG] Hovers refuse to work

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#5398] opened 2023-12-28 15:43 UTC
### Short Description of the issue:

https://github.com/tsunamayo/Starship-EVO/assets/56371294/c399bf09-e2b8-45a0-98cb-7b1ffb89b3cf

as you can see in this video despite all of the settings being at max the bike refuses to take off or even tilt when i hit E or Q

### Steps to reproduce the issue:

my hovers were working just fine however after spawning a hover off the workshop it didn't work so I restarted and now none of my hovers work 
...

### Environment
- Starship EVO version: 23w52b

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/13787777/Player.log)
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/13787778/Player-prev.log)

**Comment by TIKIRobo** [comment] 2023-12-28 15:47
![image](https://github.com/tsunamayo/Starship-EVO/assets/56371294/030fb29e-c8ca-46c4-9b97-b6ed5a9606cd)
Kyna has this to say which unfortunately i can't replicate as the 5th restart fixed things magically

**Comment by kynamats** [comment] 2023-12-28 16:01
![image](https://github.com/tsunamayo/Starship-EVO/assets/89156468/44ffecd1-e02f-4111-ad54-ae357172712b)
this is an example of a stalled entity which should be just fine. unfortunately it doesn't seem bound to particular entities of blueprints, just seems to be a random chance on entity spawn. I think this is likely the same bug as #5342

**Comment by BigBadKangaroo** [comment] 2023-12-28 16:34
> ![image](https://private-user-images.githubusercontent.com/89156468/293236972-44ffecd1-e02f-4111-ad54-ae357172712b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3ODEyMTIsIm5iZiI6MTcwMzc4MDkxMiwicGF0aCI6Ii84OTE1NjQ2OC8yOTMyMzY5NzItNDRmZmVjZDEtZTAyZi00MTExLWFkNTQtYWUzNTcxNzI3MTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDE2MjgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1Y2RlNGQwMDQxZWRmZTExMjBiNWNlNjU0MzdkNzZjMDZjMjA3Zjc4MWVjMzU4ZGIyMzFlNzYyMjgwYTU3ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kaIHVaGGatbZqTDOit3fPxqN_MnFxAHrSa9jsuyR3a0) this is an example of a stalled entity which should be just fine. unfortunately it doesn't seem bound to particular entities of blueprints, just seems to be a random chance on entity spawn. I think this is likely the same bug as #5342

I noticed this bug too, but I couldn't make out what's causing it. Didn't play much in the recent time and I usually play in "older/outdated" worlds so I thought that might be the cause.
The best fix for me was just to restart the game and everything was fine after that.

**Comment by tsunamayo** [comment] 2023-12-28 23:17
@TIKIRobo Thanks, yes I saw that a couple of time too, it is unfortunately very random and will be tricky to fix. I keep you guys posted.

**Comment by tsunamayo** [comment] 2024-02-19 23:35
I think it should be fixed in current update. Thanks

**Closed by tsunamayo** 2024-02-19 23:35 UTC
Labels: Bug
