### ISSUE TITLE
player camera frozen

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#3348] opened 2020-12-08 17:41 UTC
### Short Description of the issue:
i was entering my ship and my player camera froze but i could still move but it didnt show, the same happend when i got out the yoke
...

### Steps to reproduce the issue:
get in a ship and try and fly it, also try when leaving

### Environment
- Starship EVO version: 20w49a
- Graphics Card: rtx2060

### Additional information:
![ezgif com-gif-maker 12](https://user-images.githubusercontent.com/74992043/101520279-8b45b600-3984-11eb-86fb-1f16a2d45d0a.gif)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5660814/output_log.zip)
had to zip the file, wouldnt upload it other wise

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment] 2020-12-08 23:42
@KINGrimson Okay I am not 100% sure but it should be fixed in 20w50a. (I was not able to reproduce this).

**Closed by tsunamayo** 2020-12-08 23:42 UTC
Labels: Bug
