### ISSUE TITLE
Odd graphical bug after a long line of dragged blocks.

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Starship-EVO#951] opened 2018-10-09 23:28 UTC
### Short Description of the issue:
So I decided to try and drag a lot of blocks out to test things like performance in terms of bigger ships and found this odd graphical issue. I don't know the exact length but I will include the blueprint so you can investigate further. Also of note is that there is an 18th row (This may be a miscount on my part kind of hard to tell atm) on the last stretchy block. Which is impossible as they are limited to 17. However, this 18th row still has a hitbox and destroying it destroys the whole shape. When you continue past the odd issue the texture mess continues. Also worth noting is that only the plane on the border has the extra row. I think it may be related to an issue from the original builds where you could only place blocs 1000m away from the core. The last image shows that if you use a child entity the issue is resolved, this was the case with the old issue also.
...

### Steps to reproduce the issue:
Make a longship using the stretchy technology.
Or load the one included.
...

### Environment
- Skywanderers version: New build
- Graphics Card: GTX 1060

### Additional information:
![image](https://user-images.githubusercontent.com/43644633/46704268-29f9ef00-cc22-11e8-820c-b4ac52509795.png)
![image](https://user-images.githubusercontent.com/43644633/46704378-a096ec80-cc22-11e8-9dd5-297a08091a09.png)
![image](https://user-images.githubusercontent.com/43644633/46704463-01bec000-cc23-11e8-8f9b-6d952df7cc4e.png)
![image](https://user-images.githubusercontent.com/43644633/46704567-84e01600-cc23-11e8-99c5-dfda5bb046e8.png)

Ship download:
[Long ship.zip](https://github.com/tsunamayo/Skywanderers/files/2462554/Long.ship.zip)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment] 2018-10-10 06:34
Hi, so the 1km limit is normal and due to code. At one point I will add shipyards for gameplay reasons, so we will have a maximum size anyway, and it will be < 2km as the game cant handle ship that big =( 
For the second part:
Also of note is that there is an 18th row (This may be a miscount on my part kind of hard to tell atm) on the last stretchy block. Which is impossible as they are limited to 17. 
=> I am not sure to reproduce / understand the issue, if you can help me. 
Thanks

**Comment by Garrett-C** [comment] 2018-10-10 09:16
I think that second part was more of a miscounting error on my part. I went back and recounted and I think it is just 17. Hard to tell without some form of indication while placing. 

Also I thought the game would be able to handle bigger ships now that the new tech exists. Given that you could make a 17m^3 block I thought that this would increase max ship size a bit.

**Comment by TheCuriousSkeleton** [comment] 2018-10-11 17:43
How did you get onto the new update?

**Comment by tsunamayo** [comment] 2020-06-30 01:03
I think this should be fixed in next update. Thanks!

**Closed by tsunamayo** 2020-06-30 01:03 UTC
Labels: Bug
