### ISSUE TITLE
23w29b - Inventory Issues (ongoing)

### ISSUE THREAD

**Issue by DrizztCode** [tsunamayo/Starship-EVO#5159] opened 2023-07-18 11:50 UTC
### Short Description of the issue:
Hello! :-)

i know it's been a while - but i am back, and hoping to help out with some bug testing

also - absolutely loving the new planets - you are a genius and a maker of magical wonders :-)

anyway - as you may remember, i tend to focus on the survival features such as mining, fuel and inventories

i have frequently experienced issues with inventory flow

but currently i am seeing some specific things:

1. assembler not pulling from or pushing to connected inventories (inventories often only showing in the transfer window from the cargo container direction - i.e the container can see the assembler but not vice versa)
2. inventory not switching when selecting from the drop down transfer menu (title changes but not contents)
3. collectors causing inventory to disappear instead of expelling (moves from right to left and counts down when it gets to the far left, but does not drop out of the hopper)
4. collectors not pulling from connected inventories when set to expel (very frequent - only very occasionally works - breaks again quickly)

various other things are happening too - but these are probably the big hitters - and are almost always present - although sometimes on rare occasions i have managed to get a collector pulling from a container and expelling onto a belt
...

### Steps to reproduce the issue:

just try settings up a smelting and assembling line, which pulls the initial ore from a container

i will provide more detailed info and videos if this is not something of which you are currently aware

but i am finding it every time i try and set up production - with it being almost impossible in natural gravity (ore is falling through belts if it does get expelled) - and rarely working using ship/station gravity in space or on an asteroid

and i have never managed to get the assembler to pull from or push to containers

please do let me know if/when you need more details

thanks again for all the awesome work - and these planets are phenomenal! :-) 
...

### Environment
- Starship EVO version: 23w29b
- Graphics Card: RTX 2060

### Additional information:

if/when requested

**Comment by Foofaspoon** [comment] 2023-07-19 12:21
I had all of this issues yesterday as well, in addition when collecting occasionally you would get an item that just seemed to freeze on the way in (nothing was full) and hover in the air. You would also get phantom items that were 'stuck' in the collectors opening, but couldn't be interacted with.

**Comment by tsunamayo** [comment] 2023-07-22 01:57
@DrizztCode Hi, I cant reproduce issue 4, are you doing something specific? Do you reproduce this issue right away? The big problem is that whenever an issue happen in the inventory system, all sort of other random issues could happens. They are not the one to fix, only the first one is important (the one who introduce the data inconsticency)
Thanks

**Comment by tsunamayo** [comment] 2023-07-22 06:48
@DrizztCode Hi, it should be fixed for 23w29e maybe except for the 3), I was not able to reproduce. Thanks

**Closed by tsunamayo** 2023-07-22 06:48 UTC
Labels: Bug

**Comment by DrizztCode** [comment] 2023-07-24 23:53
> @DrizztCode Hi, I cant reproduce issue 4, are you doing something specific? Do you reproduce this issue right away? The big problem is that whenever an issue happen in the inventory system, all sort of other random issues could happens. They are not the one to fix, only the first one is important (the one who introduce the data inconsticency) Thanks

> @DrizztCode Hi, it should be fixed for 23w29e maybe except for the 3), I was not able to reproduce. Thanks

awesome work on 1 and 2 - assembler is now pulling from containers and the transfer window is working (tested on latest - i was a bit late and missed 23w29e)

as for 3 and 4 - i am guessing they are connected - and it makes sense that there is a trigger bug
just now i had the collector expelling for a moment - but i had the mining tool selected - and it was pulling the ore - so i backed off - and the ore entered the furnace - but very soon after than ore stopped being expelled - or even pulled to the collector - but it was disappearing from the container

the mining tool issue is not the catalyst i think, since i had this stuff happen without ever using the mining tool (and i will raise another issue about the mining tool - because i think the collecting effect is getting stuck on the player even when they change from the tool) - but the issue may be to do with bricks getting pulled through surfaces or entering inventories in strange ways

anyway - i shall investigate and raise a ticket if i can get some more info

but really wonderful work on the assembler, transfer interface and everything else - many thanks - survival is so close i can taste it :-)
