### ISSUE TITLE
Cannot load a blueprint in certain resolutions (1768x992)

### ISSUE THREAD

**Issue by Rexxios** [tsunamayo/Starship-EVO#2609] opened 2020-07-02 19:20 UTC
### Short Description of the issue: 
Cannot load any blueprints while using certain resolutions

### Steps to reproduce the issue: 
Load a game (new or old), spawn starter block, use the block (F default), attempt to 
click on a blueprint (nothing happens).

### Environment
- Starship EVO version: 20w27b
- Graphics Card: Nividia 1060 6B

### Additional information: Worked in previous update, have not tested a new blueprint from current update.

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4866219/output_log.txt)

**Comment by tsunamayo** [comment] 2020-07-02 23:20
Okay, do you have a problem to click on your character in the load menu? Also to confirm do you have any issue with Graphics ? UI Post effect toggled off? Thanks

**Comment by tsunamayo** [comment] 2020-07-06 03:14
@Rexxios I cant reproduce this, is this resolution a native resolution? Thanks

**Comment by tsunamayo** [comment] 2020-07-06 04:34
Okay as I think it is was an issue only with UI post effect it will be fixed in 20w28a as these post effects will disappear. Thanks

**Closed by tsunamayo** 2020-07-06 04:34 UTC
Labels: Bug
