### ISSUE TITLE
Weird box around deadzone BUG

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#2628] opened 2020-07-04 22:02 UTC
### Short Description of the issue:
When flying a ship in the new update a weird transparent box appears around the deadzone that coves up things like the interaction menu for landing pads as well as the landing pads outlines  
...

### Steps to reproduce the issue:
Get in a ship select a larding pad and move your deadzone over the interaction menu/outline of landing space and then the outline will be covered up by an "invisible" box.
...

### Environment
- Starship EVO version: 20w27d
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
![BOX 3 0](https://user-images.githubusercontent.com/56371294/86521519-b5f47700-be06-11ea-9614-606252eb00e7.JPG)

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4874003/output_log.txt)

**Comment by StarrKiss** [comment] 2020-07-04 23:02
Duplicate of https://github.com/tsunamayo/Starship-EVO/issues/2623 , post it there + close this.

**Closed** 2020-07-04 23:22 UTC
