### ISSUE TITLE
[Bug] Can't click on certain menu buttons/items

### ISSUE THREAD

**Issue by Tezlz** [tsunamayo/Starship-EVO#1777] opened 2020-04-19 12:35 UTC
### Short Description of the issue:

Can't click on certain items in menus such as the button you click on when choosing a character, or when attempting to spawn a blueprint via the drone it doesn't seem to notice that my mouse is hovering over any of the buttons

### Steps to reproduce the issue:

Open Skywanderers, create a new character, save it, exit the game. Start the game again and try to join the character again. 

### Environment
- Skywanderers version: 20w16c
- Graphics Card: GTX 1060 6GB

### Additional information:

Attempting to join an existing character:
![nv3HnxDjGW](https://user-images.githubusercontent.com/36267770/79687589-debd9500-8237-11ea-8570-08b546b1ea07.gif)

Output log:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4498943/output_log.txt)

**Comment by tsunamayo** [comment] 2020-04-21 23:46
So by exiting the game you mean exiting to Desktop or exiting to main menu? Thanks

**Comment by Tezlz** [comment] 2020-04-22 06:48
I meant exiting to desktop but it doesn't make any difference whether you quit to menu or desktop with this bug

**Comment by tsunamayo** [comment] 2020-04-22 07:12
Where you in fullscreen mode or windowed?

**Comment by Tezlz** [comment] 2020-04-22 07:28
I was in fullscreen, I just tried windowed and it still doesn't work. 
I also tried updating to the latest patch and when attempting to spawn in a blueprint there's still the same problem. I did however notice that with the latest update it does detect when I'm hovering over the dropdown menus to select whether the ai is aggressive or passive which it didn't do before. So something must have changed with those buttons that made them work

**Comment by tsunamayo** [comment] 2020-04-23 02:41
And to be sure @Tezlz you are reproducing that all the time?
Also there seems to be a small overlay layer from your windows, I wonder if that could have an impact.
I cant reproduce so its hard to track down. Is there any things specific about your setup? Thanks

**Comment by Tezlz** [comment] 2020-04-23 06:46
Yes the bug is happening all the time, which means that I can barely play the game as I need to create new characters everytime and lose all my progress on builds.

As for any overlay being in the way I thought at first that it may have been discords overlay messing things up, as it has done that to games before. But after closing discord in the background and also closing as many background programs as I could the problem persisted. I can try to run windows in safe mode later as that will disable all programs and see if that would make a difference.

There is also nothing specific really about my setup, I have a Ryzen 5 3600 CPU and a GTX 1060 6 GB GPU, only thing that stands out a bit is that I haven't activated my Windows yet (which you probably noticed from the "activate windows" watermark in my original GIF), I'm not sure if that is the reason though as one of my friends hasn't activated their windows either and the game is working as it should on their end.

I also did some debugging on my own and trying to figure out what was different about these buttons that made them not work while all the others still work. Being a programmer myself I would guess that what makes these buttons different is that you probably have a list of characters that the player has created, and are creating one of these:
![character_list](https://user-images.githubusercontent.com/36267770/80067499-73bcd880-852d-11ea-9b7a-3a613b027a0c.png)
for every character in that list. Considering that the buttons to press to spawn in a blueprint don't work either and they are probably done in the same way this is the only thing that I could think of that make these buttons different from all other ones. That is however just my guess as a beginner programmer

Sorry about the wall of text, I just want to provide you with as much info as possible so you can solve it as soon as possible. :)

**Comment by tsunamayo** [comment] 2020-04-23 08:35
I think it is the same issue as #1813... What is your screen resolution? Are you running the game in full screen mode? Thanks

**Comment by Tezlz** [comment] 2020-04-23 08:52
Yes that seems to be the same issue! Good to know that it's not just me. I am running the game at 1920x1200 resolution and in fullscreen, I have however tested it in windowed and it didn't seem to make a difference

**Comment by Tezlz** [comment] 2020-04-23 08:57
I just tried changin the resolution to 1920x1080 and now it is working as it should, so that seems to have been the problem

**Comment by tsunamayo** [comment] 2020-04-23 09:00
What is your monitor natural definition? It is 1920x1200?

**Comment by Tezlz** [comment] 2020-04-23 09:00
yes

**Comment by tsunamayo** [comment] 2020-04-23 09:35
Okay I tried to play with my resolution setting but was not able to reproduce the issue. I keep you posted.

**Comment by tsunamayo** [comment] 2020-04-24 13:51
@Tezlz could you please tell me if you have the issue with the native resolution AND in graphic settings / UI Post effect deactivated? Thanks

**Comment by Tezlz** [comment] 2020-04-24 14:09
The issue got fixed when I deactivated UI Post effects in 1920x1200

**Comment by tsunamayo** [comment] 2020-04-25 00:22
@Tezlz okay good we are making slow progress.

**Comment by tsunamayo** [comment] 2020-04-25 01:47
okay I think I might have found the culprit. Fix will be in 20w17d, I ping you once the patch is live. Thanks!

**Comment by tsunamayo** [comment] 2020-04-25 07:33
@Tezlz  a fix should be live in 20w17d, can you tell me if that fixed the issue? Thanks

**Comment by Tezlz** [comment] 2020-04-25 11:25
Yup that seems to have fixed it!

**Comment by tsunamayo** [comment] 2020-04-25 12:56
Okay neat! Glad I got that one before ea ;)

**Closed by tsunamayo** 2020-04-25 12:56 UTC
Labels: Bug

**Comment by Tezlz** [comment] 2020-04-26 15:06
@tsunamayo It would appear that I did not test it enough before I said that it was fixed, I just noticed that the bug is still there when attempting to join a server and when trying to spawn in a blueprint
