### ISSUE TITLE
[BUG} Flood light's effect showing through the ship

### ISSUE THREAD

**Issue by Slyack** [tsunamayo/Starship-EVO#4323] opened 2021-12-05 07:56 UTC
Flood light's effect is visible through the ship while controlling it.

- Starship EVO version: Static/Default
![image](https://user-images.githubusercontent.com/60378099/144738478-dacc6f79-f8ab-4b24-86b6-b416842c48ce.png)

**Comment by pinesh** [comment] 2021-12-05 22:55
Duplicate issue: #4249

**Comment by tsunamayo** [comment] 2021-12-05 23:45
@Slyack Hi, thanks for booking this. Yes it is a duplicate, I will close this issue. I still havent figured out the cause, I will update the other case when I do...
Thanks

**Closed by tsunamayo** 2021-12-05 23:45 UTC
Labels: Bug
