### ISSUE TITLE
More Connector Blocks (Copy/Paste lite)

### ISSUE THREAD

**Issue by JLAMontoya** [tsunamayo/Starship-EVO#2817] opened 2020-08-27 02:06 UTC
### Suggestion

I had an idea cross my mind when thinking of the simplest means of adding the heavily discussed copy/paste functionality to the game quickly and safely.

We have large connectors for stations, which players can pass through. Once attached via these connectors, any ship or structure is permanently bonded with the parent ship or structure.

Giving us smaller connectors would allow us to make turret blueprints and simply attach them at small connectors on the parent ship. Or landing pad blueprints, engine nacelles, whatever. Simply delete the connector blocks afterward and fill in the empty space with normal blocks.

This would give us a quicker, already-functional alternative to copy/paste, which still needs to be developed. I'm not suggesting this replace that functionality, but you expressed concern that it might not fit the game- these connectors can easily be a thing, and partly already are.

Edit: This would mean a single brick-sized connector, and a 1x1x1 block connector, specifically.

**Comment by CaptainKronos** [comment] 2020-08-27 02:07
I concur with this suggestion, similar to the merge block of space engineers

**Comment by MrNobodyX3** [comment] 2020-08-27 22:25
That or the weld tool from Scrap Mechanic. Where you select the face of the object your connecting to the face of another object and everything attached will teleport and connect to the 2nd object selected

**Comment by CaptainKronos** [comment] 2020-08-27 22:44
yes

**Comment by ZachZent** [comment] 2020-08-28 00:26
To add, I'd like to see a 30, 45, 60 degree connector rather than only straight connectors. As great as they are, you are kind of limited to square-like stations and any angle requires an annoyingly long time to angle even a basic hallway if it is possible in the first place. That is unless you want to build an entire module on a child entity, but then the union will come out and break your legs. Since a module is a new grid anyway, why not skip the child entity middle man allowing for easier creation of more "rounded" stations. For example something like this where as before you would only be able to do 4 comfortably.
![200px-Mammalian_Habitat](https://user-images.githubusercontent.com/36980446/91507682-3a54fa80-e88a-11ea-9091-72a43d602683.jpg)

**Comment by CaptainKronos** [comment] 2020-08-28 00:36
I concur with zach, would add to the creative freedom of the game

**Comment by tsunamayo** [comment] 2020-08-29 00:23
Yes but the problem is not the implementation, but the performance cost. What you are suggesting is way more terrible performance wise so I wont go that route. Weld tool is something different as it is merging the grid. I will test the proper copy paste soon, stay tuned.
@ZachZent yes it make sense! But I was actually wondering in nuking these doors if I go the prefab route, and then giving a smaller docking port, and the eyelid door a a separate door that could be used anywhere. Then you can make a prefab docking port design and use the prefab system.
Closing this as it wont happens this way! 
Cheers

**Closed by tsunamayo** 2020-08-29 00:23 UTC
Labels: Suggestion
