### ISSUE TITLE
can't spawn or load in to world

### ISSUE THREAD

**Issue by Slate-gorgon** [tsunamayo/Starship-EVO#1813] opened 2020-04-23 04:05 UTC
### Short Description of the issue:
after the last update from last night i can not load/deleted any world even the one i just saved and i can not spawn ships even ones i just saved
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4520145/output_log.txt)

...

### Steps to reproduce the issue: i just started up the game an had to make a new player and i place a stater block go an try to load a Bp an nothing happen

...

### Environment
- Skywanderers version:  pre-alpha 20w17b
- Graphics Card: radeon rx 570

### Additional information:
i've tryed uninstalling rebooting and nothing helped 
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment] 2020-04-23 05:47
Okay lets fix this.
1) First can you confirm  that you can build a new entity from a starter block, exit the game, go back and see the entity?
2) Then the blueprint you want to load quite old? Are you putting the starter block high enough in the air? They might just be appearing under the surface.
3) can you send me your blueprint? 
Thanks!

**Comment by Slate-gorgon** [comment] 2020-04-23 07:13
Tsunamayo so i can save new bp but i cant load them or join a world that i just left from nor deleted it
so i cant test the leaving and rejoining and as for the BP it was mabe last night Pre update

and as for the BP i was trying its dosen't want to send over here ill try the Discor under Cmdr Slate_gorgon

**Comment by Sullos** [comment] 2020-04-23 07:15
Also, I didn't think of this earlier, but when you transferred the blueprints folder over from the old version, I just want to check you didn't transfer anything else over? Like the character folder or anything else. If so, maybe try deleting them. Try deleting everything but your blueprints folder, from the Save_Data folder.

**Comment by tsunamayo** [comment] 2020-04-23 07:27
So if I understand correctly, you create a new character, exit the game, then cant load in? Could you try the below?
1) Create a new character
2) start a new random build
3) exit the game to desktop
4) Load the character back
=> can you load the character? If not what happens?

**Comment by Slate-gorgon** [comment] 2020-04-23 07:35
nothing happen no error or crash just dose nothing :(

**Comment by tsunamayo** [comment] 2020-04-23 07:37
so you just see the loading screen and it doesnt stop?

**Comment by Slate-gorgon** [comment] 2020-04-23 07:37
dosen't even start

**Comment by tsunamayo** [comment] 2020-04-23 07:40
The game doesnt start? You cant click on the player name? Could you give more detail mate it is hard for me to know what is going on...

**Comment by Slate-gorgon** [comment] 2020-04-23 07:56
ill post a short clip of what is going on for you

**Comment by Slate-gorgon** [comment] 2020-04-23 07:59
https://youtu.be/tWXLFAA6RSU

**Comment by tsunamayo** [comment] 2020-04-23 08:02
So when you click on the little arrow to the left nothing happens. Do you confirm it is the issue? Thanks

**Comment by tsunamayo** [comment] 2020-04-23 08:34
I think it is the same issue as #1777... What is your screen resolution? Are you running the game in full screen mode? Thanks

**Comment by Slate-gorgon** [comment] 2020-04-23 08:34
the arrow to the lft is to start that world right if so then yes i clicked it on all of them and nothing happen

**Comment by Slate-gorgon** [comment] 2020-04-23 08:59
:(

**Comment by tsunamayo** [comment] 2020-04-23 09:02
It seems it is linked to the screen resolution. We are making progress! What is your screen resolution? Can you try 1920x1080? Thanks

**Comment by Slate-gorgon** [comment] 2020-04-23 10:20
that did it

**Comment by tsunamayo** [comment] 2020-04-23 10:51
Okay I am doing further test, I cant reproduce the issue unfortunately so it might take a few build to get a definited fix. Thanks

**Comment by Slate-gorgon** [comment] 2020-04-23 10:55
so i did some testing an i try other Res and a few broke it in the same way i dont know if its drivers or what

**Comment by tsunamayo** [comment] 2020-04-24 13:52
@Slate-gorgon could you please tell me if you have the issue with the native resolution AND in graphic settings / UI Post effect deactivated? Thanks

**Comment by tsunamayo** [comment] 2020-04-25 07:32
@Slate-gorgon  a fix should be live in 20w17d, can you tell me if that fixed the issue? Thanks

**Comment by tsunamayo** [comment] 2020-04-25 12:57
Okay other player confirmed issue was fixed. Thanks!

**Closed by tsunamayo** 2020-04-25 12:57 UTC
Labels: Bug
