### ISSUE TITLE
[BUG] Decals disappearing on child entities 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#2900] opened 2020-09-05 16:41 UTC
### Short Description of the issue:
After placing down decals on the bottom of my landing gear i realized that the decals that I had placed on the other landing gear were disappearing i could still hover my mouse over them to highlight them but visually they were gone    
...

### Steps to reproduce the issue:
place multiple decals on different child entities on the same craft  
...

### Environment
- Starship EVO version: 20w36c
- Graphics Card: AMD Radeon RX 5600 XT 

### Additional information:
![ezgif com-optimize (4)](https://user-images.githubusercontent.com/56371294/92309617-efa74280-ef5b-11ea-9797-e0841f68cc68.gif)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5178361/output_log.txt)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by TIKIRobo** [comment] 2020-09-05 16:43
After restarting the game all decals reappeared so idk what happened but it fixed itself i guess

**Comment by TIKIRobo** [comment] 2020-09-05 16:44
never mind they did comeback but as soon as i started placing more they disappeared  again

**Comment by TIKIRobo** [comment] 2020-09-05 16:47
Ok one last correction it does NOT just happen on just child entities **_WHEN PLACING DECALS PREVIOUS DECALS MAY DISAPPEAR_**

**Comment by tsunamayo** [comment] 2020-09-06 00:25
@TIKIRobo could you please give me your ship I will try to reproduce. Thanks!

**Comment by TIKIRobo** [comment] 2020-09-06 01:17
[CV1-05-01.zip](https://github.com/tsunamayo/Starship-EVO/files/5178950/CV1-05-01.zip)
@tsunamayo  here you go!

**Comment by tsunamayo** [comment] 2020-09-07 05:52
I think the issue should be fixed in next patch 20w37a. (I was not able to reproduce but I fixed the faulty line).
Tell if that is not the case if you still see the issue after next patch!
Thanks

**Closed by tsunamayo** 2020-09-07 05:52 UTC
Labels: Bug

**Comment by cloudrambler** [comment] 2020-09-09 13:04
I have had the same problem. A build with decals on a main and child entity. Often the decals seem to be linked in pairs, fix one and the other disappears and vice versa. Also exporting and importing as blueprint seems to destabilise further. Will see if my issues are resolved by 20w37a also.
