### ISSUE TITLE
[BUG] Own blueprints in the starterblock have dissapeared

### ISSUE THREAD

**Issue by MadTheDog** [tsunamayo/Starship-EVO#3039] opened 2020-10-06 07:13 UTC
### Short Description of the issue:
My own blueprints have disappeared from the starter block spawning menu. The blueprints are still in the "`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`" location, and workshop blueprints still show up, therefore it is likely just a pathfinding error in the new system as of 20w41a.

...

### Steps to reproduce the issue:
Place a stater block
Open it and find that all your blueprints are not there
...

### Environment
- Starship EVO version: 20w41a
- Graphics Card: GTX 1060

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5331933/output_log.txt)

**Comment by ZachZent** [comment] 2020-10-06 07:20
Can confirm. I don't have any ws blueprints downloaded and my the starter block is empty

**Comment by tsunamayo** [comment] 2020-10-06 09:00
@ZachZent @MadTheDog what are you seing in the blueprint folder? Thanks

**Comment by ZachZent** [comment] 2020-10-06 09:04
![](https://cdn.discordapp.com/attachments/271723356795961345/762963423817629706/unknown.png)

**Comment by tsunamayo** [comment] 2020-10-06 09:06
@ZachZent no in your explorer window? It is working fine on my side...

**Comment by tsunamayo** [comment] 2020-10-06 09:07
Also does everybody has this issue?

**Comment by tsunamayo** [comment] 2020-10-06 09:07
Also does everybody has this issue?

**Comment by MadTheDog** [comment] 2020-10-06 10:04
This is in the blueprint folder, there are folders which contain the blueprint, and the old system:
![image](https://user-images.githubusercontent.com/16719231/95187850-f085fb00-07cb-11eb-9108-ccf7de0093ce.png)

**Comment by Kaiser-Indrasil** [comment] 2020-10-06 11:15
If you're using the Stable Branch, you just have to unpack the files from each individual folder.

**Comment by MadTheDog** [comment] 2020-10-06 11:43
You can also upload your existing ships to the workshop as private and then paste them from there as a band-aid solution if you want to play on experimental.

**Comment by Kaiser-Indrasil** [comment] 2020-10-06 15:43
Since 41A I cannot spawn local blueprints whatsoever, both from a folder and from files.

**Comment by Aiwii** [comment] 2020-10-06 20:30
I am also having this issue

**Comment by tsunamayo** [comment] 2020-10-06 23:17
okay do you guy get that issue right away? Like you load the game, put a starter block and try to load something? thanks

**Comment by Aiwii** [comment] 2020-10-07 00:10
I played the game for the first time in about a week today and the first time I opened the starter block it was empty other than the WS blueprints I saved

**Comment by tsunamayo** [comment] 2020-10-07 00:17
@Aiwii I understood how to reproduce: you guy exported a blueprint first (that was already existing), then opened the load menu.
The code didnt not account for that, that why it was fine for me and not you.
So for the time being the fix constist in deleting the old blueprint you exported on the root of the blueprint folder, not the new one in the folder.
To make it more clear:

Say you exported "My Ship", the folder will go like this:

\Blueprints\My ship.mps  <-- old version, to delete!
\Blueprints\My ship\My ship.mps <-- new version, to keep!

Once there is a single instance there is no issue.
Thanks

**Comment by tsunamayo** [comment] 2020-10-07 01:59
Issue fixed in 20w41b. thanks all!

**Closed by tsunamayo** 2020-10-07 01:59 UTC
