### ISSUE TITLE
[Bug] Collector will not collect ores while hovercraft is controlled

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#6133] opened 2024-11-24 18:33 UTC
### Short Description of the issue:
In building a small miner hovercraft, the Collector does not seem to gather ores until I release control of the hovercraft. The ores bunch up in front of the Collector but do not go into its inventory
https://imgur.com/a/tz28b5m
This testing was done in Survival mode

PS - sorry for the awful handling of the hovercraft lol, I didn't realise the mass of the turret barrel would be computed in real time to unbalance the hovercraft! Very cool

### Steps to reproduce the issue:
- Load in attached bp
- Mine some ores with the Mining Laser Turret
- Watch the ores gather in front of the Collector, not going inside its inventory
- Release control of the hovercraft, and the ores will be collected properly

### Environment
- Starship EVO version: 24w46a
- Graphics Card: RX 6700XT

### Additional information:

[JankyHover.zip](https://github.com/user-attachments/files/17894410/JankyHover.zip)
[Player.log](https://github.com/user-attachments/files/17894411/Player.log)

**Comment by Crimson-Artist** [comment] 2024-11-24 19:18
This is definitely a general collector bug. I experienced this while testing in creative.

**Comment by tsunamayo** [comment] 2024-11-24 23:46
@ProPeach Thanks, man you went on a rampage! I will work on all those bugs. Yes now children entity mass update the parent center of gravity in real time, it was done sometime back.

**Comment by ProPeach** [comment] 2024-11-24 23:59
Appreciate it! Yes this is actually thr first time I've been able to play survival properly, so I guess I had a fresh experience coming into it. Hope they don't give you too much trouble o7

**Comment by ProPeach** [comment] 2024-11-25 05:09
Yes you're right, it's coal and stone rather than an ore to be honest

**Comment by tsunamayo** [comment] 2024-11-26 00:38
@ProPeach I tried it, it is just the collector that is getting full from my test... Turns out 1m3 is not a lot...

**Comment by ProPeach** [comment] 2024-11-26 10:38
@tsunamayo so I emptied both the Cargo Container and the Collector in the hovercraft and tried again, and true the Collector is actually accepting ore, just very slowly. However, I still do think there is at least a ore flow rate difference when you release the controls of the hovercraft. If you mine a large amount of rock and just wait for it to be picked up by the Collector, it takes a long while and seems to get jammed up by a large clump of ore. But if you mine the same amount of ore and then let go of the controls, it is picked up far quicker by the Collector.

Similarly, mining using just the turret without entering the Hovercraft Computer, the Collector seems to pick up much faster.
![711980_20241126103342_1](https://github.com/user-attachments/assets/2060d895-38d2-41bc-984c-e0d1b95e9267)
 It could be that something about the hovercraft hovering about is making it hard for the ore to make it into the Collectors inventory?

**Comment by tsunamayo** [comment] 2024-11-27 00:39
Hum I will try to reproduce that. Where you moving a bit while in control? They need to be present in front of the collector to be picked up.

**Comment by ProPeach** [comment] 2024-11-27 00:50
Stationary or not didn't seem to make a difference. At one time I noticed the craft was drifting backwards away from the ore being attracted, so I tried moving forward slowly to see if forcing the Collector into contact with the ore would help but that didn't appear to change the rate of pickup.

**Comment by tsunamayo** [comment] 2024-11-29 01:08
@ProPeach Hi, it should be fixed for next update 24w48a. Cheers

**Closed by tsunamayo** 2024-11-29 01:08 UTC
Labels: Bug
