### ISSUE TITLE
[Bug] Child Entities missing/relocated on load.

### ISSUE THREAD

**Issue by pinesh** [tsunamayo/Starship-EVO#3883] opened 2021-06-20 18:07 UTC
### Short Description of the issue:
previously present child entities (and by proxy any sub-entities) seem to have vanished from present and spawned blueprints. The missing entities, are consistent across and respawns  (and always the same entity. The vanished entities still have the lower section of their mechanism (e.g. hinge frame or rotor base) but anything attached is seemingly not present, and attempting to put a fresh child entity in the same spot will also vanish again on load and seemingly cause other entities to vanish.

EDIT: 
There is some indication that these missing entities have not simply vanished, but have found themselves relocated to other child mechanisms. had the relocation failed, they simply despawn. This is evident on the commented blueprint where a top panel has found its way to the side. 

EDIT 2:
This issue only seems to be affecting ships built in the last day or two. Older blueprints are unaffected. 

...

### Steps to reproduce the issue:
Spawn in any ship with child entities and look for missing/relocated children
...

### Environment
- Starship EVO version: 21w24a
- Graphics Card: RTX 3080

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![image](https://user-images.githubusercontent.com/14081996/122683907-123add00-d1b7-11eb-88fc-3c18d0f219eb.png)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6682837/Player.log)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/6682838/output_log.txt)

**Comment by TwoNiner29** [comment] 2021-06-20 18:13
Encountering the same problem, here's a blueprint with an example:
[Ravager Class Cruiser.zip](https://github.com/tsunamayo/Starship-EVO/files/6682844/Ravager.Class.Cruiser.zip)

**Comment by BigBadKangaroo** [comment] 2021-06-20 19:00
Already did a post mentioning this: #Child Entitys on BP don't spawn in #3877

**Comment by pinesh** [comment] 2021-06-20 19:09
> 
> 
> Already did a post mentioning this: #Child Entitys on BP don't spawn in #3877

This post points out that the child entities are not nessercarily not spawning but might instead be relocating.

**Comment by milan-t** [comment] 2021-06-20 21:55
Similar thing happened to me after loading world yesterday. Upper door on sliding rail relocated from front of the spaceship to back and visually merged with piston. I found door by using link tool because child entity has a hinge connected to temporal switch.

Spaceship's blueprint loaded correctly. I started new world and loaded blueprint there. Later I exported new version of spaceship.

Now as I writing this comment I started game, loaded my current world (created yesterday) and find out that it happened again but with different part of spaceship. Now piston part is missing.  When I change piston position moving sound plays endlessly.

Unfortunately the part of same piston is also missing after loading blueprint in new world. I'm not sure if the spaceship was ok in the time of export. Previous version of the spaceship looks ok after loading.

Yesterday I also needed to resolve few mechanical collisions on doors that started occuring after game update. Most of collisions were obvious but piston retracting into hole of its size had no visible obstacle. I rebuilt it few times until it started working again. Now moving part disappeared.

Here are some screenshots:
*Front upper door missing*
![20210619155725_1](https://user-images.githubusercontent.com/65783423/122686902-f6b1ef80-d213-11eb-8468-571ca0f165b6.jpg)

*Front upper door found relocated to back*
![20210619155744_1](https://user-images.githubusercontent.com/65783423/122686903-f74a8600-d213-11eb-9868-4ad9b0281af6.jpg)

*Sliding rail without moving part*
![20210619160755_1](https://user-images.githubusercontent.com/65783423/122686905-f7e31c80-d213-11eb-95f1-a8c77ea1e251.jpg)

*Merger of piston and moving part of sliding rail*
![20210619160932_1](https://user-images.githubusercontent.com/65783423/122686906-f7e31c80-d213-11eb-8dcb-a2fa240db367.jpg)

*Current occurrence of issue - missing part of piston with child entity (simple hull block)*
![20210620222236_1](https://user-images.githubusercontent.com/65783423/122687500-08e15d00-d217-11eb-8fa5-6d25f8ac4bfe.jpg)

**Comment by RockefellerDoctor** [comment] 2021-06-20 22:09
Had something similar happen to my ship. I had a MASSIVE gun mounted on a piston that extended from a weapon bay once the doors opened.

When I loaded my blueprint  for it, the turret was instead now located on a decorative piston located in the cockpit. Which looks hilarious because now the cockpit just has a massive gun clipping through it.

**Comment by tsunamayo** [comment] 2021-06-21 00:14
I am on it, btw I hope you guy had a recent backup / blueprint of your ship as there was some save issue...

**Comment by pinesh** [comment] 2021-06-21 00:39
> 
> 
> I am on it, btw I hope you guy had a recent backup / blueprint of your ship as there was some save issue...

Should we consider writing off any modifications to the affected blueprints?

**Comment by tsunamayo** [comment] 2021-06-21 00:45
Not sure yet... I havent been able to reproduce this bug yet...

**Comment by tsunamayo** [comment] 2021-06-21 00:47
@TwoNiner29 Where I am supposed to look? If any one of you have a blueprint or world for me to look at... Thanks

**Comment by pinesh** [comment] 2021-06-21 01:27
In the interest of solving this quickly, Im attaching my affected blueprint, and screenshots of the missing parts.
dh-11 was saved in the problematic version, while 10 was saved before the latest patch but remains affected by the issue.


![image](https://user-images.githubusercontent.com/14081996/122695315-e50d1f80-d1f4-11eb-849c-e0f24b638eb9.png)
![image](https://user-images.githubusercontent.com/14081996/122695331-f2c2a500-d1f4-11eb-8e3a-495fc136f7c0.png)
[dh-new11-BUGGED.zip](https://github.com/tsunamayo/Starship-EVO/files/6683482/dh-new11-BUGGED.zip)
[dh-new10.zip](https://github.com/tsunamayo/Starship-EVO/files/6683485/dh-new10.zip)

**Comment by pinesh** [comment] 2021-06-21 01:27
> 
> 
> @TwoNiner29 Where I am supposed to look? If any one of you have a blueprint or world for me to look at... Thanks

**Comment by tsunamayo** [comment] 2021-06-21 01:55
@pinesh do you have an even older save? One that was saved before this update.

**Comment by tsunamayo** [comment] 2021-06-21 01:56
also do you recall having done some modification to these entity (like opening the entity screen), or not at all? Thanks

**Comment by pinesh** [comment] 2021-06-21 01:59
certainly, here's an older version.  I built the missing platforms, and the missing back engines sometime either before the build menu or after. I can't account for that missing segment on the engine, however, as I recall modifying all of them. The platforms still present were built before the missing side, but i believe with the current build menu. 

<-This one is dated as saved on the 12th.
[dh-new5.zip](https://github.com/tsunamayo/Starship-EVO/files/6683586/dh-new5.zip)

**Comment by pinesh** [comment] 2021-06-21 02:01
this one is from when I first built the pads.
[dh-new7-pads.zip](https://github.com/tsunamayo/Starship-EVO/files/6683590/dh-new7-pads.zip)

**Comment by tsunamayo** [comment] 2021-06-21 02:12
yep sorry the issue was:
- tweak a rotor via the menu
- save or export that blueprint.
At that point the children entity id is lost. Nothing I can do to get that on back... I hope you guys have all recent backup...
It was linked to a weakness in my code that somehow did not had any impact up until the recent refactor.
I didnt spotted that because everything was loading fine on my side (as you need to edit a mechanism first)- sorry one that one...

**Comment by tsunamayo** [comment] 2021-06-21 02:14
So fixed for 21w24b, except that your save are corrupted... =(

**Closed by tsunamayo** 2021-06-21 02:14 UTC
Labels: Bug

**Comment by pinesh** [comment] 2021-06-21 02:18
> 
> 
> So fixed for 21w24b, except that your save are corrupted... =(

quick clarification, can I replace the missing/broken entities with fresh ones on the broken blueprint or is the entire blueprint itself corrupted?
