### ISSUE TITLE
starting area broken

### ISSUE THREAD

**Issue by Azathoh-the-blind-idiot-god** [tsunamayo/Starship-EVO#2894] opened 2020-09-04 20:40 UTC
### Short Description of the issue:
starter area broken. buildings start invisible and follow me.

### Steps to reproduce the issue:

create a new world and paint one of the starter buildings.

### Environment
- Starship EVO version: 20W36c
- Graphics Card: rtx 5700

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5176843/output_log.txt)

[test2.zip](https://github.com/tsunamayo/Starship-EVO/files/5176853/test2.zip)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment] 2020-09-04 22:42
Hi, this sounds bad. I cant reproduce the issue, did you break something or else? Also can you reproduce this that all the time with a new character? Thanks

**Comment by Xain5755** [comment] 2020-09-05 16:04
I'm having a similar issue, the building doesn't follow me but everything starts out invisible with every new character.  I used F5 to get out of the building and started to build my own structure.  At first everything worked fine but once I got a decent build going every block I tried placing was invisible.

**Comment by tsunamayo** [comment] 2020-09-06 00:09
@Xain5755 you have a log file to show? On which version are you? There an issue that have been causing this recently, it will be fixed in next patch. Thanks

**Closed** 2020-12-01 06:08 UTC
Labels: Bug
