### ISSUE TITLE
[Bug] Gravity not working on Torus.

### ISSUE THREAD

**Issue by SageThe13th** [tsunamayo/Starship-EVO#2035] opened 2020-05-12 10:36 UTC
When I load a BP on the Torus gravity doesn't effect it. Even if the BP has a starter block on it that I delete it stays in the air. When I quit out of the world and start it up again, gravity starts working on the vehicle again.

version: prealpha 20w20a

![Float](https://user-images.githubusercontent.com/58193603/81674159-60a57600-9412-11ea-8975-5b32acd5e53f.png)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4614971/output_log.txt)

**Comment by tsunamayo** [comment] 2020-05-12 11:05
Duplicate of #2013, issue is already fixed and will be available in 20w20b. Thanks!

**Closed by tsunamayo** 2020-05-12 11:05 UTC
Labels: Bug
