### ISSUE TITLE
[BUG] Damage is disabled 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#4173] opened 2021-09-12 20:15 UTC
### Short Description of the issue:
ships do not do damage, the beams just stop on the shields but dont damage them
...

### Steps to reproduce the issue:
try shooting another ship 
...

### Environment
- Starship EVO version:21w36a 
### Additional information:

https://user-images.githubusercontent.com/56371294/133001523-daecce1d-a7f1-43b4-89a9-1a1709e2fcfb.mp4

**Comment by tsunamayo** [comment] 2021-09-18 23:48
@TIKIRobo I cant reproduce this... Do you repro 100% of the time? Could you send me your Player.log? Thanks

**Comment by Reason147** [comment] 2021-09-19 00:08
confirmed I noticed this as well, player ships seem to have this problem.

**Comment by TIKIRobo** [comment] 2021-09-19 00:16
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7190798/Player.log)
@tsunamayo yea i can get this one every time, pre neovox guns still do damage tho (like the guns on the Canis-Class Interceptor)

**Comment by tsunamayo** [comment] 2021-09-30 00:32
@TIKIRobo Do you reproduce in latest build? I think there was a fixed issue with beams.

**Comment by TIKIRobo** [comment] 2021-09-30 00:46
@tsunamayo yep i can still reproduce it

**Comment by tsunamayo** [comment] 2022-01-21 06:26
@TIKIRobo Sorry mate to ping you again, I still cant quite reproduce, do you get this in 22w03c? Thanks

**Comment by Reason147** [comment] 2022-01-21 13:44
No, the problem seems to have been resolved in the new updates. Whatever you did fixed it!!

**Closed** 2022-11-07 06:11 UTC
Labels: Bug, Cannot Reproduce
