### ISSUE TITLE
Monitor link to turret bug

### ISSUE THREAD

**Issue by Regnion** [tsunamayo/Starship-EVO#3011] opened 2020-09-30 18:13 UTC
### Short Description of the issue:
You can link the flat monitor to a turret computer and control the turret, while controlling the yoke. It functions perfectly. However, when you spawn this vehicle in, the monitor stops functioning unless you completely re-link everything. It does not disconnect or delete any existing links- it simply doesn't respond, you can't do anything with it.

I do not know if this happens with other monitors as well.

Note: This also occurs when you exit the game and return, the monitor ceases to work even though it worked perfectly before.

...

### Steps to reproduce the issue:
The turret computer is controlling a camera as well. Link a flat monitor to a turret computer that is controlling all the required axes, plus weapons and a camera. You are driving the vehicle with a yoke. You should be able to use the monitor as well, in order to choose between controlling the vehicle, and controlling both with seeing through a camera. Save the vehicle as a blueprint. Spawn in the vehicle. The turret control system no longer functions. Relink everything, including the turret computer's link to the camera (this is an important step).

I am confident the camera is involved somewhere in the break, as resetting the camera's link is required to force the monitor to function again.

...

### Environment
- Starship EVO version: 20w36B
- Graphics Card: Nvidia GeForce GTX 970

### Additional information:

See attached blueprint, it has the control scheme I prescribe above.
[RegnionLightTankBlueprint.zip](https://github.com/tsunamayo/Starship-EVO/files/5307496/RegnionLightTankBlueprint.zip)

**Comment by Gliese-832-c** [comment] 2020-09-30 21:31
Try switchting to the experimental branch and seeing if the issue is gone there.

**Comment by tsunamayo** [comment] 2020-09-30 23:32
@Gliese-832-c Hi, no need to tell them to do that, this is not an issue that should be fixed in experimental. 
@Regnion Thanks for the detailed test case, I keep you posted!

**Comment by Regnion** [comment] 2020-10-01 01:04
@tsunamayo I have found that:

Linking the monitor to the camera, and then linking the camera to the turret computer, works perfectly and consistently. It feels backwards, you'd think the computer would be the basis, but this method works.

**Comment by tsunamayo** [comment] 2020-10-01 01:12
I think the issue first is that you can control both a spaceship and a turret with camera, which makes no sense.

**Comment by tsunamayo** [comment] 2020-10-01 02:05
@Regnion issue fixed for 20w40b. It was really bugged, it is amazing you managed to make it work at all actually ;) Cheers

**Closed by tsunamayo** 2020-10-01 02:05 UTC
Labels: Bug
