### ISSUE TITLE
Symmetry: Incorrect Decal Orientation

### ISSUE THREAD

**Issue by Misteropie** [tsunamayo/Starship-EVO#2722] opened 2020-07-27 16:37 UTC
### Short Description of the issue:

Certain decals will not hold the same orientation that they were placed in when mirrored with mirror mode on walls facing opposite directions.

### Steps to reproduce the issue:

1. Start a build with mirror mode. Doesn't need to be complex can just be a wall as I've used in my screenshots.
2. Place any one of these decals: Vent Holes, Creased Vert Decals, Triangle, Circle Lines
3. The decals MUST be flat parallel to the mirror wall / symmetry tool as they orient correctly when perpendicular to the mirror wall.

### Environment
- Starship EVO version: 20w31a

### Additional information:

https://i.imgur.com/vmiUr6d.png https://i.imgur.com/jJI9Ghv.png

**Comment by Tocks13** [comment] 2020-07-28 11:41
Duplicate of #2514 but in a newer Version.
Don't remember wether it should have been fixed since then.

**Comment by tsunamayo** [comment] 2022-01-19 22:55
Hi, this is fixed in recent versions. thx

**Closed by tsunamayo** 2022-01-19 22:55 UTC
Labels: Bug
