### ISSUE TITLE
[BUG] De-spawn not working

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#4740] opened 2022-06-18 21:00 UTC
As of build 22w14a, I cannot get the ship de-spawn function to work. It seems to delete a few blocks, then leaves the rest of the ship visible. I think the physicality of the ship is gone (collisions etc.).

**Comment by tsunamayo** [comment] 2022-06-22 00:20
@cloudrambler Okay I cant reproduce that issue also. Do you get this 100% of the time? Can you give me a log file to investigate?
Thanks

**Comment by cloudrambler** [comment] 2022-06-22 16:10
This particular de-spawn failure only happened once and I cannot replicate it either.

**Comment by tsunamayo** [comment] 2022-06-23 06:26
@cloudrambler Okay I will close this as I cant investigate. If it happen again can you send the error.log too? Thanks

**Closed by tsunamayo** 2022-06-23 06:26 UTC
Labels: Cannot Reproduce
