### ISSUE TITLE
[BUG] Items in assembler turned into hull blocks and hull blocks started spewing out of the character.

### ISSUE THREAD

**Issue by SovietSponge** [tsunamayo/Starship-EVO#5565] opened 2024-02-21 09:26 UTC
### Short Description of the issue:
I was crafting hull blocks using the assembler, suddenly there were 64 of them where there should've been one.
Upon trying to take them out of the assembler every other item took on the appearance of hull blocks and upon exiting the assembler my character started spewing out dozens of hull blocks.

Looks similar to #5562 ?
### Steps to reproduce the issue:
I genuinely have no idea how this happened.
### Environment
- Starship EVO version: 24w07a
- Graphics Card: RTX 3060 Ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![image](https://github.com/tsunamayo/Starship-EVO/assets/66131361/a8af743f-1619-4cb1-ba9c-daca7a23cab0)

https://github.com/tsunamayo/Starship-EVO/assets/66131361/262b564c-a735-4afa-b5be-f76f6c4d69f9

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14357284/Player.log)

**Comment by tsunamayo** [comment] 2024-02-22 00:00
@SovietSponge Hi, yes it is the same bug, it is hard for me to fix as I cant reproduce. So this time it was with the assembler, you where crafting hull block? Any other crafting running elsewhere? Thanks

**Comment by tsunamayo** [comment] 2024-02-22 00:11
@SovietSponge Also could you tell me what are the setting of your assembler? Ie push / pull settings.

**Comment by SovietSponge** [comment] 2024-02-22 09:00
@tsunamayo Sorry for not seeing this sooner.
No other crafting was running at the time and my settings are these, I changed nothing since I don't know what any of them do.
![image](https://github.com/tsunamayo/Starship-EVO/assets/66131361/2c4a2676-541e-4846-a836-e2ca908885cc)

I also just reloaded the world and noticed that its back to normal besides the assembler's inventory being gone, my hotbars are all fine and there's no giant pile of bug blocks anywhere.
If I were to encounter the bug again do you think sending over the character file would be useful?

**Comment by tsunamayo** [comment] 2024-02-26 03:35
@SovietSponge Hi, I am not 100% confident but I think (hope?) this issue will be fixed for 24w09b. Tell me if you ever meet that again!

**Closed** 2024-02-28 04:54 UTC
Labels: Bug
